### ISSUE TITLE
DropdownMenu 下拉菜单

### ISSUE THREAD

**Issue by shilnjie** [Tencent/tdesign-mobile-vue#1002]
### tdesign-mobile-vue 版本

1.0.0-rc.5

### 重现步骤

单选下拉菜单和多选下拉菜单组合使用的时候，点击展开多选面板，然后关闭，文字会消失
![Uploading ad7b70a1ef92e58c1f096201bbd66c3.png…]()

### 期望结果

单选下拉菜单和多选下拉菜单组合使用的时候，点击展开多选面板，然后关闭，文字不会消失

```[tasklist]
### Tasks
```

## IssueShoot
- 预估时长: 3
- 期望完成时间: 2023-08-09 00:00:00 +0000 UTC
- 开发难度: 中
- 参与人数: 1
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by shilnjie** [comment]
![image](https://github.com/Tencent/tdesign-mobile-vue/assets/96516385/a2588bb8-1e3b-424f-821f-76282a98989f)

**Comment by anlyyao** [comment]
duplicated with #1003
