### ISSUE TITLE
[layout] mobile中没有找到layout

### ISSUE THREAD

**Issue by BanKnight** [Tencent/tdesign-mobile-vue#1016]
### tdesign-mobile-vue 版本

1.0.0-rc.6

### 重现步骤

我使用桌面端的vue-next代码，提示找不到layout

<template>
  <t-space direction="vertical">
    <div>
      <t-layout>
        <t-header>Header</t-header>
        <t-content>Content</t-content>
        <t-footer>Footer</t-footer>
      </t-layout>
    </div>

    <div>
      <t-layout>
        <t-header>Header</t-header>
        <t-layout>
          <t-aside>Aside</t-aside>
          <t-content>Content</t-content>
        </t-layout>
        <t-footer>Footer</t-footer>
      </t-layout>
    </div>

    <div>
      <t-layout>
        <t-header>Header</t-header>
        <t-layout>
          <t-content>Content</t-content>
          <t-aside>Aside</t-aside>
        </t-layout>
        <t-footer>Footer</t-footer>
      </t-layout>
    </div>

    <div>
      <t-layout>
        <t-aside>Aside</t-aside>
        <t-layout>
          <t-header>Header</t-header>
          <t-content>Content</t-content>
          <t-footer>Footer</t-footer>
        </t-layout>
      </t-layout>
    </div>
  </t-space>
</template>

### 期望结果

正确编译并且使用layout

## IssueShoot
- 预估时长: 12
- 期望完成时间: 2024-5-24 00:00:00 +0000 UTC
- 开发难度: 中
- 参与人数: 1
- 需求对接人: anlyyao
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by anlyyao** [comment]
@BanKnight mobile vue 目前还没支持 layout 组件哈

**Comment by anlyyao** [comment]
> @anlyyao 那么请问正式版会支持吗？ 毕竟这个功能比较重要，而实现又相对简单，目前想要试用下都会因为没有这个组件而不太想动手。
正在排期，会尽快支持到～
