### ISSUE TITLE
[checkbox] 横向多选框无法响应reactive定义的数据

### ISSUE THREAD

**Issue by Digoler** [Tencent/tdesign-mobile-vue#1023]
### tdesign-mobile-vue 版本

1.0.0-rc.6

### 重现链接

https://github.com/Digoler/TDesin-Checkbox

### 重现步骤

pnpm install 运行项目打开即可，相关描述已经写在页面中

### 期望结果

点击能够正常响应数据

### 实际结果

点击多选框无反应，reactive定义的复杂数据类型无变化

### 系统版本

Window11

### Node版本

16

### 补充说明

null

**Comment by anlyyao** [comment]
emmmm····，不支持reactive([])不是组件的 bug。
v-model 不支持reactive([])，它的更新原理是重新赋值来替换原始值，所以要使用 ref 或者对象属性(比如 v-model="obj.a")。
参考：
[vModel源码](https://github.com/vuejs/core/blob/c03459b9b6d3c18450235bc4074a603677996320/packages/runtime-dom/src/directives/vModel.ts)
[Checkbox used v-model doesn't work on a reactive variable](https://github.com/vuejs/core/issues/2662)
[Checkbox v-model array mutation](https://github.com/vuejs/core/issues/2700)
