### ISSUE TITLE
1.0.0 正式版的引入有bug

### ISSUE THREAD

**Issue by ComradeFu** [Tencent/tdesign-mobile-vue#1039]
### tdesign-mobile-vue 版本

1.0.0

### 重现步骤

比如 tdesign-mobile-vue\es\upload\index.js 中，引用：
import '@/_common/js/upload/main';

@ 会使得 vite 解析为我的工程目录，报路径找不到。
怀疑是开发在打包的时候没有正确替换掉 @ alias

### 期望结果

能正确引入

### 实际结果

vite 报错找不到 _common 有关的文件

### 框架版本

Vue3

### 系统版本

win11

**Comment by anlyyao** [comment]
@ComradeFu 已处理。正在发布1.0.1， 1.0.0将废弃

**Comment by anlyyao** [comment]
1.0.1已发布，可以安装了～

> @ComradeFu 已处理。正在发布1.0.1， 1.0.0将废弃
