### ISSUE TITLE
[Calendar] 设置了value但是定位在minDate

### ISSUE THREAD

**Issue by yiludege** [Tencent/tdesign-mobile-vue#1043]
### tdesign-mobile-vue 版本

1.0.1

### 重现步骤

Calendar只要设置minDate之后，不管  value 是多少，打开日历组件时间定位在minDate，而不是value的地方

## IssueShoot
- 预估时长: 1
- 期望完成时间: 2023-09-26 00:00:00 +0000 UTC
- 开发难度: 低
- 参与人数: 1
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by anlyyao** [comment]
@yiludege #1042 已处理，但 #1043提到的：设置minDate之后，不管 value 是多少，打开日历组件时间定位在minDate，这一处我们没能复现，辛苦在确认一下问题，可以贴上你的可复现代码到下方链接，然后把更新的链接贴上来～

 https://stackblitz.com/edit/fkgcr7?file=src%2Fdemo.vue
