### ISSUE TITLE
[t-icon] 点击事件 onClick 不正常失效

### ISSUE THREAD

**Issue by ComradeFu** [Tencent/tdesign-mobile-vue#1052]
### tdesign-mobile-vue 版本

1.0.1

### 重现步骤

直接使用tsx渲染，比如：
```tsx
<t-icon name="user-password" size="2em" onClick={onClickWechatLogin}></t-icon>
```

onClick 不会回调。

但是使用无网模式的引入，正常：
```tsx
import { LogoWechatStrokeIcon } from 'tdesign-icons-vue-next';
const logoWechatStrokeIcon = () => h(LogoWechatStrokeIcon, {size:'2em', onClick: ()=>{console.log(`click !!!`)}})

// 渲染
 return () => (<div class="loginIconGroup">
      {
          curLoginMode.value === "wechat" ?
          undefined
          :
          logoWechatStrokeIcon()
         
      })
  </div>
```

### 期望结果

理应都有正确的 onclick 回调。

### 实际结果

没有回调

### 补充说明

官网：https://1_0_0-rc_6-tdesign-mobile-vue.surge.sh/mobile-vue/components/icon
的预览，点击下面的 icon 也无反馈，感觉是同一个问题。时间繁忙就没办法帮忙做 code-review 了。

**Comment by anlyyao** [comment]
@ComradeFu  

1. 采用```<t-icon name="user-password" size="2em" onClick={onClickWechatLogin}></t-icon>```时，请确认是否有真确引入，图标是否正确显示。
2. 官网图标展示模块点击是有效的哈，可能是缺了Message提示所以觉得没有反馈（这里会补齐）。 你可以官网点击
<img width="221" alt="截屏2023-08-22 10 38 35" src="https://github.com/Tencent/tdesign-mobile-vue/assets/51158141/39f4703a-4cc5-45fb-8470-39a6f641b955">
后 paste 到别处，

**Comment by ComradeFu** [comment]
> 

真切引入，没有问题。icon 的 name 也是复制进去的。同时，页面也有显示出来，只是 onClick 无效。

**Comment by anlyyao** [comment]
> > 
> 
> 真切引入，没有问题。icon 的 name 也是复制进去的。同时，页面也有显示出来，只是 onClick 无效。

方便在这个链接里面贴上你的可以复现的代码，保存，并提供一下新的链接吗、
https://stackblitz.com/edit/qzorvm?file=src%2Fdemo.vue

**Comment by ComradeFu** [comment]
> > > 
> > 
> > 
> > 真切引入，没有问题。icon 的 name 也是复制进去的。同时，页面也有显示出来，只是 onClick 无效。
> 
> 方便在这个链接里面贴上你的可以复现的代码，保存，并提供一下新的链接吗、 https://stackblitz.com/edit/qzorvm?file=src%2Fdemo.vue

好，稍等

**Comment by ComradeFu** [comment]
> > > 
> > 
> > 
> > 真切引入，没有问题。icon 的 name 也是复制进去的。同时，页面也有显示出来，只是 onClick 无效。
> 
> 方便在这个链接里面贴上你的可以复现的代码，保存，并提供一下新的链接吗、 https://stackblitz.com/edit/qzorvm?file=src%2Fdemo.vue

hello，我写了最简的 demo，用的是 tsx 写法。但线上IDE没有环境编译，同样的代码在我本地是没有回调的。

**Comment by ComradeFu** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 真切引入，没有问题。icon 的 name 也是复制进去的。同时，页面也有显示出来，只是 onClick 无效。
> > > 
> > > 
> > > 方便在这个链接里面贴上你的可以复现的代码，保存，并提供一下新的链接吗、 https://stackblitz.com/edit/qzorvm?file=src%2Fdemo.vue
> > 
> > 
> > hello，我写了最简的 demo，用的是 tsx 写法。但线上IDE没有环境编译，同样的代码在我本地是没有回调的。
> 
> 有仓库嘛？

稍等忙完准备一个！

**Comment by ComradeFu** [comment]
奇怪了，重启 vscode 之后确实没有再出来这个问题。
可能是玄学 bug 。
