### ISSUE TITLE
[ImageViewer] 两指缩放时图片重叠

### ISSUE THREAD

**Issue by anlyyao** [Tencent/tdesign-mobile-vue#1058]
### tdesign-mobile-vue 版本

1.0.2

### 重现链接

https://tdesign.tencent.com/mobile-vue/mobile.html#/image-viewer

## IssueShoot
- 预估时长: 5
- 期望完成时间: 2023-09-24 00:00:00 +0000 UTC
- 开发难度: 高
- 参与人数: 1
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by fennghuang** [comment]
已领取
