### ISSUE TITLE
[DateTimePicker] 打包后不支持PC端选择，手机端正常

### ISSUE THREAD

**Issue by chenshiming1113** [Tencent/tdesign-mobile-vue#1059]
### tdesign-mobile-vue 版本

1.0.2

### 重现步骤

打包发布

### 期望结果

日期选择弹出层可以滚动或拖动选择。

### 实际结果

PC端不能滚动，手机端可以

### Node版本

16.20.1

**Comment by anlyyao** [comment]
@chenshiming1113  mobile vue 是一个移动端的件库，组件目前只监听了移动端的 touch 事件，没有监听 pc 端 mouse 事件。

**Comment by chenshiming1113** [comment]
> @chenshiming1113 mobile vue 是一个移动端的件库，组件目前只监听了移动端的 touch 事件，没有监听 pc 端 mouse 事件。

https://tdesign.tencent.com/mobile-react/components/picker，这个选择器感觉顺滑很多，文档体验也比较好。希望这个vue文档也改进下。

**Comment by anlyyao** [comment]
> > @chenshiming1113 mobile vue 是一个移动端的件库，组件目前只监听了移动端的 touch 事件，没有监听 pc 端 mouse 事件。
> 
> [https://tdesign.tencent.com/mobile-react/components/picker，这个选择器感觉顺滑很多，文档体验也比较好。希望这个vue文档也改进下。](https://tdesign.tencent.com/mobile-react/components/picker%EF%BC%8C%E8%BF%99%E4%B8%AA%E9%80%89%E6%8B%A9%E5%99%A8%E6%84%9F%E8%A7%89%E9%A1%BA%E6%BB%91%E5%BE%88%E5%A4%9A%EF%BC%8C%E6%96%87%E6%A1%A3%E4%BD%93%E9%AA%8C%E4%B9%9F%E6%AF%94%E8%BE%83%E5%A5%BD%E3%80%82%E5%B8%8C%E6%9C%9B%E8%BF%99%E4%B8%AAvue%E6%96%87%E6%A1%A3%E4%B9%9F%E6%94%B9%E8%BF%9B%E4%B8%8B%E3%80%82)


具体对文档改进的意见是？？ 文档层面 mobile react 的体验和 mobile vue 的差异是？
<img width="1606" alt="截屏2023-08-30 14 11 44" src="https://github.com/Tencent/tdesign-mobile-vue/assets/51158141/868c8b53-68bd-4524-a66b-8a7a04137e9f">
<img width="1581" alt="截屏2023-08-30 14 11 54" src="https://github.com/Tencent/tdesign-mobile-vue/assets/51158141/35a4393d-a182-45e2-9597-fccff96a0706">
