### ISSUE TITLE
[t-cell-group] 不兼容以前版本，无法使用自定义class

### ISSUE THREAD

**Issue by ry0513** [Tencent/tdesign-mobile-vue#1066]
### tdesign-mobile-vue 版本

1.0.2

### 重现链接

https://stackblitz.com/edit/ozqsnq-ftrqoi?file=src%2Fdemo.vue

### 重现步骤

```
<template>
  <div class="bg">
    <t-cell-group bordered class="mb">
      <t-cell title="单行标题" arrow hover />
    </t-cell-group>
    <t-cell-group bordered class="mb">
      <t-cell title="单行标题" arrow hover />
    </t-cell-group>
    <t-cell-group bordered class="mb">
      <t-cell title="单行标题" arrow hover />
    </t-cell-group>
  </div>
</template>
<style>
* {
  margin: 0;
  padding: 0;
}
.bg {
  background: #f1f1f1;
  height: 100vh;
}
.mb {
  margin-bottom: 16px;
}
</style>
```
1.0.0-rc.6 版本
链接：https://stackblitz.com/edit/ozqsnq-ajk8hh?file=src%2Fdemo.vue
效果如下
![1 0 0-rc 6](https://github.com/Tencent/tdesign-mobile-vue/assets/44745967/43bd753e-c0bf-4dd3-b2c8-570d0769f981)
1.0.2 版本
链接：https://stackblitz.com/edit/ozqsnq-ftrqoi?file=src%2Fdemo.vue
效果如下
![1 0 2](https://github.com/Tencent/tdesign-mobile-vue/assets/44745967/6ab98e68-f3f3-4321-a700-ef138cb81bc5)

### 期望结果

希望1.0.2可以继续支持写自定义 class
1.0.0-rc.6 版本中
![image](https://github.com/Tencent/tdesign-mobile-vue/assets/44745967/9c243332-88e4-4abb-9e24-99cc08ce7307)

### 实际结果

1.0.2 不支持自定义的class
![image](https://github.com/Tencent/tdesign-mobile-vue/assets/44745967/eb217041-3fcf-4ccc-8471-9dd1bb27e51b)

### 框架版本

Vue(3.2.47)

### 浏览器版本

Chrome   116.0.5845.97

### 系统版本

win11 22H2

### Node版本

V16.20.0

### 补充说明

项目上使用自定义class， 升级tdesign-mobile-vue版本后导致样式不兼容

**Comment by n0liu** [comment]
<img width="715" alt="image" src="https://github.com/Tencent/tdesign-mobile-vue/assets/44688300/ede132b2-a8c4-449b-a61f-d19ba04040ef">
我刚看了源码，默认class 被视作透传 attribute，到组件的根元素上，但是现在有两个节点。所有不能渲染，我建议 @ry0513 增加一个prop 来接受用户传递的 class.

**Comment by anlyyao** [comment]
> <img alt="image" width="715" src="https://user-images.githubusercontent.com/44688300/264531827-ede132b2-a8c4-449b-a61f-d19ba04040ef.png"> 我刚看了源码，默认class 被视作透传 attribute，到组件的根元素上，但是现在有两个节点。所有不能渲染，我建议 @ry0513 增加一个prop 来接受用户传递的 class.

是的，此外还注意到一条警告 `runtime-core.esm-bundler.js:41 [Vue warn]: Extraneous non-props attributes (class) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. `， 因此决定在组件外层重新包一层 div(see  #1069 )，确保根template只有一个子节点。
```
<div>
    <div v-if="titleContent" :class="`${name}__title`">
      <t-node :content="titleContent" />
    </div>
    <div :class="contentClass">
      <slot />
    </div>
  </div>
```
