### ISSUE TITLE
[t-picker] modelValue 在types中显示是可选，实际上如果不绑定会报组件错误

### ISSUE THREAD

**Issue by ComradeFu** [Tencent/tdesign-mobile-vue#1068]
### tdesign-mobile-vue 版本

1.0.2

### 重现步骤

只要不指定 v-model （modelValue）即可。
```tsx
<t-picker />
```

### 期望结果

有时候我不需要处理 modelValue，只关注 onConfirm。
如果 movelValue 实在是必须，也应该有更友好的说明，不是让人去 debug 。。

### 实际结果

![image](https://github.com/Tencent/tdesign-mobile-vue/assets/14305742/fc7dbb20-7a3a-4648-bc8e-a9bcb077e475)
上图是类型说明可选。
实际运行：
![image](https://github.com/Tencent/tdesign-mobile-vue/assets/14305742/2a1fa6c6-b642-4eed-9b36-3608e61a243d)

## IssueShoot
- 预估时长: 1
- 期望完成时间: 2023-09-03 00:00:00 +0000 UTC
- 开发难度: 低
- 参与人数: 1
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by anlyyao** [comment]
@ComradeFu 感谢反馈，确实是可选项，我这边处理一下～
