### ISSUE TITLE
[t-pull-down-refresh] 下拉刷新组件与 t-swipe-cell 同时使用时，会使左滑跟竖直滑动的互斥失效。

### ISSUE THREAD

**Issue by ComradeFu** [Tencent/tdesign-mobile-vue#1075]
### tdesign-mobile-vue 版本

1.0.2

### 重现步骤

当触发了左滑，或者竖直滑动的事件时，应该互斥。
我看到源码也做了类似的处理：
![image](https://github.com/Tencent/tdesign-mobile-vue/assets/14305742/182e6b91-c3ab-431e-b12a-b8aba503b968)

这在正常的原生 html 是成立的。但一旦被嵌套到 t-pull-down-refresh 就不行了。
Demo: https://github.com/ComradeFu/tdesign-vue-mobile-demo/blob/main/src/views/Home.vue。

这个还蛮影响体验的，麻烦看下。

### 期望结果

应该是统一的特征

### 实际结果

又可以左滑又可以上下滑

## IssueShoot
- 预估时长: 3
- 期望完成时间: 2023-09-11 00:00:00 +0000 UTC
- 开发难度: 中
- 参与人数: 1
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by fennghuang** [comment]
已领取 issue
