### ISSUE TITLE
[hover.ts] 公共组件 Hover 的scroll 事件 handler 请考虑加如  passive: true

### ISSUE THREAD

**Issue by ComradeFu** [Tencent/tdesign-mobile-vue#1076]
### tdesign-mobile-vue 版本

1.0.2

### 重现步骤

passive: true 可以让滑动在移动端更有效率。
比如：
```tsx
el.addEventListener('scroll', handleScroll, { passive: true });
```

但实际上 shared/hover.ts 的代码没有加上：
![image](https://github.com/Tencent/tdesign-mobile-vue/assets/14305742/314d9e24-19e6-423a-b1d9-e3b1065c9846)

### 实际结果

![image](https://github.com/Tencent/tdesign-mobile-vue/assets/14305742/e3130b27-c063-4b31-be38-c68470b5f494)

**Comment by anlyyao** [comment]
@ComradeFu  我看到你好几个 issue 其实都关注到源码了，有兴趣的话可以一起共建呀，欢迎 pr ～

**Comment by ComradeFu** [comment]
> @ComradeFu 我看到你好几个 issue 其实都关注到源码了，有兴趣的话可以一起共建呀，欢迎 pr ～

感谢邀请，但最近任务重，有空一起！
