### ISSUE TITLE
[t-popup] 请教一个问题，我在小程序中 webview 显示网页，无法限制webview 本身的上下滑动。但 popup 显示时是可以的。

### ISSUE THREAD

**Issue by ComradeFu** [Tencent/tdesign-mobile-vue#1081]
### tdesign-mobile-vue 版本

1.0.2

### 重现步骤

请问是怎么做到的。。
我用的就是官方示例。
https://tdesign.tencent.com/mobile-vue/components/picker

然后就可以很神奇的阻止小程序把webview 上下拖离一定的边界了。。

**Comment by anlyyao** [comment]
@ComradeFu  不太确定你具体的使用场景。 但popup是有锁住背景滚动的，你可以看一下源码
