### ISSUE TITLE
[ImageViewer 图片预览] 只预览一张图打开没有图

### ISSUE THREAD

**Issue by starsBugs** [Tencent/tdesign-mobile-vue#1083]
### tdesign-mobile-vue 版本

1.0.2

### 重现步骤

ImageViewer 图片预览 预览数组变量 如果是一条链接 预览不显示图片 只显示遮罩层，但是右滑就有图，划过来之后 图片就自动跳回去了

### 期望结果

ImageViewer 图片预览 可以在只有一个图片需要预览时，正常预览

### 框架版本

Vue(3.3.4)

### 浏览器版本

私有化企业微信窗口打开

### 系统版本

miui14.0.6

### Node版本

v18.14.2

### 补充说明

![image](https://github.com/Tencent/tdesign-mobile-vue/assets/57882716/89202aa7-ee5f-43cc-b513-8fe423ca41d8)
![image](https://github.com/Tencent/tdesign-mobile-vue/assets/57882716/8394570a-248a-41e1-ad38-b956da549950)

**Comment by anlyyao** [comment]
@starsBugs  1.0.3 有处理，更新版本试试～
