### ISSUE TITLE
[SideBar] 使用插件按需导入组件控制台告警

### ISSUE THREAD

**Issue by sunshj** [Tencent/tdesign-mobile-vue#1084]
### tdesign-mobile-vue 版本

1.0.3

### 重现链接

https://github.com/sunshj/tdesign-mobile-vue-demo

### 重现步骤

使用unplugin-auto-import与unplugin-vue-components按需导入组件，当引入SideBar侧边栏组件时，控制台出现如下警告：
> [Vue warn]: Failed to resolve component: t-badge
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 

### 期望结果

控制台无警告

### 实际结果

![image](https://github.com/Tencent/tdesign-mobile-vue/assets/47186980/be1fa1a7-d023-489a-9ec3-7ad746316001)

### 框架版本

Vue(3.3.4)

**Comment by anlyyao** [comment]
@sunshj  [Vue warn]: Failed to resolve component: t-badge。 你有引入 badge组件吗？

**Comment by sunshj** [comment]
没有使用badge组件

**Comment by anlyyao** [comment]
> 没有使用badge组件

明白了 我处理一下，明天发版带上，着急的话可以暂时先引入badge解决warn
