### ISSUE TITLE
[Cascader] `onChange` 事件会重复触发且文档类型不正确

### ISSUE THREAD

**Issue by Kigoal** [Tencent/tdesign-mobile-vue#1086]
### tdesign-mobile-vue 版本

1.0.3

### 重现步骤

```vue
<script setup lang="ts">
const modelValue = defineModel<string | number>({
  required: true,
});

const visible = ref(false);

const handleChange = (_value: string | number, selectedOptions?: TreeOptionData<string | number>[]) => {
  if (selectedOptions) {
    formartModelValue.value = selectedOptions.map((item) => item.label).join(' / ');

    visible.value = false;
  }
};
</script>

<template>
  <TdCascader v-model:visible="visible" v-model="modelValue" :options="options" :title="title" @change="handleChange" />
</template>
```

### 实际结果

1.实际在每次选完的时候会触发两次，第一次必定是 `undefined` 类型， 第二次是 `TreeOptionData<string | number>[]` 类型，非文档的 `string[]` 类型。
![eb419fb9183cb28b867d332202d00fc](https://github.com/Tencent/tdesign-mobile-vue/assets/21240282/7bbd72c4-f449-483f-a4f8-58d0fdb8d5ba)

2.在没有 `props.title` 时 `t-cascader__title` 样式的高度为 `0` ，导致 `t-cascader__close-btn` 样式显示错位。
![image](https://github.com/Tencent/tdesign-mobile-vue/assets/21240282/750fedf5-9e42-427c-aec5-09bc8134c941)

3.`v-model` 、 `v-model:value` 只会使用初始值，后面值有更新时不会触发响应式

## IssueShoot
- 预估时长: 3
- 期望完成时间: 2023-09-22 00:00:00 +0000 UTC
- 开发难度: 中
- 参与人数: 1
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by bitjian** [comment]
i look look
