### ISSUE TITLE
[Input][输入框] tips不在下方显示，而是在右侧显示

### ISSUE THREAD

**Issue by starsBugs** [Tencent/tdesign-mobile-vue#1101]
### tdesign-mobile-vue 版本

1.0.4

### 重现步骤

**实际显示样式**
![image](https://github.com/Tencent/tdesign-mobile-vue/assets/57882716/33fa83a0-34f4-49f8-ac68-5b19fed1f9c6)

**文档介绍内容**
![image](https://github.com/Tencent/tdesign-mobile-vue/assets/57882716/b59ede27-0455-4f59-8897-335fadd3babb)

**代码**
![image](https://github.com/Tencent/tdesign-mobile-vue/assets/57882716/91446798-f918-400d-a2dc-5dda90892d33)

### 期望结果

希望文本提示可以到输入框下方去

**Comment by chaishi** [comment]
官网没有看到这样的问题，请提供可以重现问题的链接。或者在下方链接中复现你的问题。
https://stackblitz.com/edit/ffq7sl?file=src%2Fdemo.vue
<img width="287" alt="image" src="https://github.com/Tencent/tdesign-mobile-vue/assets/11605702/72b2ddca-1e51-418b-a2f3-b69d4cf85cb9">

<img width="175" alt="image" src="https://github.com/Tencent/tdesign-mobile-vue/assets/11605702/804d5c05-463e-4058-bf8a-25df8cfca80c">

**Comment by chaishi** [comment]
一般情况应该不会有这个问题，请再次检查项目中的 CSS，是否有哪一个样式影响到了这里。
