### ISSUE TITLE
[Swiper 轮播框] current不起作用

### ISSUE THREAD

**Issue by lysk** [Tencent/tdesign-mobile-vue#1105]
### tdesign-mobile-vue 版本

1.0.4

### 补充说明

采用web端方法：通过设置current属性值来控制轮播框播放哪一项，但并未起作用

**Comment by anlyyao** [comment]
hello，@lysk ，我这边目前 current 属性测试正常。请提供可以重现问题的链接。或者在下方链接中复现你的问题。
https://stackblitz.com/edit/48jsrb?file=src%2Fdemo.vue

<img width="223" alt="截屏2023-09-25 10 23 45" src="https://github.com/Tencent/tdesign-mobile-vue/assets/51158141/6a034106-c00a-4983-809f-51e6e0e1e3b5">


如果长时间没有提供可以重现问题的链接，issue 会被关闭

**Comment by lysk** [comment]
@anlyyao 代码已提供

**Comment by anlyyao** [comment]
<img width="1175" alt="截屏2023-10-03 10 16 42" src="https://github.com/Tencent/tdesign-mobile-vue/assets/51158141/3bb5bd9e-28a0-4931-bc4e-f55007916f84">

 有啥问题？？？

**Comment by anlyyao** [comment]
> @anlyyao 代码已提供

<img width="1175" alt="截屏2023-10-03 10 16 42" src="https://github.com/Tencent/tdesign-mobile-vue/assets/51158141/3bb5bd9e-28a0-4931-bc4e-f55007916f84">

 有啥问题？？？

**Comment by lysk** [comment]
> > @anlyyao 代码已提供
> 
> <img alt="截屏2023-10-03 10 16 42" width="1175" src="https://user-images.githubusercontent.com/51158141/272129904-3bb5bd9e-28a0-4931-bc4e-f55007916f84.png">
> 有啥问题？？？

代码被覆盖了？
就是我想实现pc这个效果https://tdesign.tencent.com/vue/components/swiper#%E6%89%8B%E5%8A%A8%E8%B7%B3%E8%BD%AC

**Comment by anlyyao** [comment]
> > > @anlyyao 代码已提供
> > 
> > 
> > <img alt="截屏2023-10-03 10 16 42" width="1175" src="https://user-images.githubusercontent.com/51158141/272129904-3bb5bd9e-28a0-4931-bc4e-f55007916f84.png">
> > 有啥问题？？？
> 
> 代码被覆盖了？ 就是我想实现pc这个效果https://tdesign.tencent.com/vue/components/swiper#%E6%89%8B%E5%8A%A8%E8%B7%B3%E8%BD%AC

我更换了第二张图，让current更明显一点，但目前测试 current是有效的。 pc的哪一种效果？自动播放？
