### ISSUE TITLE
[t-cell] rightIcon无效

### ISSUE THREAD

**Issue by beloved-zh** [Tencent/tdesign-mobile-vue#1107]
### tdesign-mobile-vue 版本

1.0.4

### 实际结果

[t-cell] rightIcon属性无效

**Comment by beloved-zh** [comment]
![image](https://github.com/Tencent/tdesign-mobile-vue/assets/52067640/e1b642c4-e16c-4b4f-96ed-6efba05d3f97)
找到原因了 是设置了 arrow  rightIcon插槽失效

**Comment by anlyyao** [comment]
> ![image](https://user-images.githubusercontent.com/52067640/269804336-e1b642c4-e16c-4b4f-96ed-6efba05d3f97.png) 找到原因了 是设置了 arrow rightIcon插槽失效

好滴 没其他问题的话，我这边就直接关闭该issue了～
