### ISSUE TITLE
[Upload] 安卓手机相册选择图片上传不支持

### ISSUE THREAD

**Issue by chenshiming1113** [Tencent/tdesign-mobile-vue#1109]
### tdesign-mobile-vue 版本

1.0.3

### 重现步骤

<t-upload
        accept="image/*"
        :action="uploadUrl"
        withCredentials
        multiple
        :max="2"
        v-model="formData.faultPhotos"
        :format-response="uploadFormatResponse"
      >
      </t-upload>

### 期望结果

支持拍照和相册

### 实际结果

安卓手机只支持拍照和最近图片，不支持相册选择上传。相册选择图片后没有效果

### Node版本

16.20.1

## IssueShoot
- 预估时长: 3
- 期望完成时间: 2023-10-02 00:00:00 +0000 UTC
- 开发难度: 中
- 参与人数: 1
- 需求对接人: anlyyao
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by fennghuang** [comment]
@chenshiming1113 请补充一下具体的安卓机型

**Comment by yaogengzhu** [comment]
我用安卓试了下，安卓机 input h5 直接拉起的话，是有一个文件选择，从文件选择进入相册即可。 如果需要那种原生的相册效果（如果这个h5 是内嵌到某个安卓壳子下的话，需要客户端支持下？）

**Comment by yaogengzhu** [comment]
我验证了下上传，是支持的哈！ 只是不要用我们提供的action 的链接， 请使用自定义的上传接口即可。如果使用自定的上传接口有问题的话，可以贴下链接~

@anlyyao 可能需要检查下action 接口

![51696481517_ pic](https://github.com/Tencent/tdesign-mobile-vue/assets/42566669/7921abf3-795a-4d4b-abbb-91dd5ee93923)

**Comment by yaogengzhu** [comment]
补充下： 如果是上传成功没有图片展示的话， 你需要format下你上传的后的返回格式, 参考 formatResponse API  @chenshiming1113

**Comment by chenshiming1113** [comment]
是公众号内置浏览器的的问题，这几天看又可以了。

**Comment by chenshiming1113** [comment]
是公众号内置浏览器的的问题，这几天看又可以了。
