### ISSUE TITLE
[swiper 轮播图] 设置placement: 'outside'，没有效果。点还是在内部。

### ISSUE THREAD

**Issue by mengyaqian** [Tencent/tdesign-mobile-vue#1110]
### tdesign-mobile-vue 版本

最新版本

### 重现步骤

设置参数  :navigation="{ type: 'dots', placement: 'outside', paginationPosition: 'bottom' }"。
顺便问一下：nextMargin参数和previousMargin参数大概什么时候可以支持。目前显示开发中。

### 期望结果

期望点可以在外侧

### 实际结果

点在内侧

## IssueShoot
- 预估时长: 8
- 期望完成时间: 2024-5-12 00:00:00 +0000 UTC
- 开发难度: 中
- 参与人数: 1
- 需求对接人: anlyyao
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by anlyyao** [comment]
任务目标：

- sfc 改 tsx
- 支持 placement: 'outside'

**Comment by anlyyao** [comment]
@mengyaqian  outside 模式已支持，可参考官网最后一个示例： https://tdesign.tencent.com/mobile-vue/components/swiper
