### ISSUE TITLE
[Stepper] 输入框支持小数

### ISSUE THREAD

**Issue by beloved-zh** [Tencent/tdesign-mobile-vue#1111]
### 这个功能解决了什么问题

输入框支持小数

### 你建议的方案是什么

[Stepper] 输入框可支持小数
## IssueShoot
- 预估时长: 3
- 期望完成时间: 2023-10-02 00:00:00 +0000 UTC
- 开发难度: 中
- 参与人数: 1
- 需求对接人: anlyyao
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by beloved-zh** [comment]
![image](https://github.com/Tencent/tdesign-mobile-vue/assets/52067640/bae07104-f03e-45d3-b86e-b99fd724b7e1)
目前 `<input type="tel" />`

**Comment by fennghuang** [comment]
已领取
