### ISSUE TITLE
在 nuxt 中几乎所有组件都会爆 window is not defined 错误

### ISSUE THREAD

**Issue by PDieE** [Tencent/tdesign-mobile-vue#1115]
### tdesign-mobile-vue 版本

1.0.5

### 重现步骤

在 nuxt 中使用按需引入的方式进行使用后在服务端渲染时会爆 window is not defined 错误，如果使用 ClientOnly 标签包裹则不会

### 期望结果

希望能更好的兼容 nuxt

## IssueShoot
- 预估时长: 5
- 期望完成时间: 2023-10-20 00:00:00 +0000 UTC
- 开发难度: 高
- 参与人数: 1
- 需求对接人: anlyyao
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by PParanoid** [comment]
@PDieE 收到反馈，确实有这个问题，需要集中处理一下，window在 ssr 时是不存在的。但应该不是所有组件都涉及，你这次具体用到了哪些组件呢？

**Comment by PDieE** [comment]
@PParanoid 目前我只尝试了 swiper image  button

**Comment by zyhnbyyds** [comment]
什么时候能支持ssr呢🤓

**Comment by anlyyao** [comment]
> 什么时候能支持ssr呢🤓

下周发版支持～

**Comment by anlyyao** [comment]
已修复于 1.2.0 版本
