### ISSUE TITLE
[Toast] 文案不居中

### ISSUE THREAD

**Issue by LikeDege** [Tencent/tdesign-mobile-vue#1116]
### tdesign-mobile-vue 版本

1.0.4

### 重现步骤

![image](https://github.com/Tencent/tdesign-mobile-vue/assets/12826345/fb88f29a-5c41-4fe5-8bad-efa58fba6408)

toast不指定theme时，文案没有居中

## IssueShoot
- 预估时长: 1
- 期望完成时间: 2023-10-11 00:00:00 +0000 UTC
- 开发难度: 低
- 参与人数: 1
- 需求对接人: anlyyao
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by anlyyao** [comment]
@LikeDege 感谢反馈，会尽快处理～

**Comment by fennghuang** [comment]
已领取
