### ISSUE TITLE
[SwipeCell 滑动单元格] 滑动双操作和三操作，在手机上最后一个操作按钮没有显示出来。

### ISSUE THREAD

**Issue by mengyaqian** [Tencent/tdesign-mobile-vue#1118]
### tdesign-mobile-vue 版本

最新版本

### 重现链接

 https://github.com/Tencent/tdesign-mobile-vue/assets/21994480/eadb0e6d-5cfa-40f6-9795-e5384fd44030

### 重现步骤

复现步骤如下：
https://github.com/Tencent/tdesign-mobile-vue/assets/21994480/eadb0e6d-5cfa-40f6-9795-e5384fd44030

### 期望结果

可以正常显示

### 实际结果

缺少最后一个操作按钮

### 浏览器版本

小米手机自带浏览器

**Comment by anlyyao** [comment]
@mengyaqian 提供一下具体机型、浏览器、浏览器版本

**Comment by fennghuang** [comment]
![image](https://github.com/Tencent/tdesign-mobile-vue/assets/89014758/104c2c94-7dcf-46d8-8fb6-4d5143d90040)
demo 里设置的 css 在浏览器里渲染的结果 width 存在小数误差引起的
