### ISSUE TITLE
[Input] 输入框在type='password'的 情况下 控制密码是否明文显示的问题

### ISSUE THREAD

**Issue by starsBugs** [Tencent/tdesign-mobile-vue#1121]
### tdesign-mobile-vue 版本

1.0.5

### 重现步骤

在输入完密码，光标离开文本框之后 就无法在点击眼睛查看明文了，只有删除掉密码，重新输入才可以，想知道为什么这么设计，现在用户使用感觉十分别扭

### 期望结果

希望可以在光标离开后 也可以点击查看明文密码

### 框架版本

3.3.4

**Comment by starsBugs** [comment]
输入完密码，光标未离开
![image](https://github.com/Tencent/tdesign-mobile-vue/assets/57882716/904ecd0d-2a93-46a8-abf9-da2a854f7b36)

光标离开
![image](https://github.com/Tencent/tdesign-mobile-vue/assets/57882716/25109cce-6f56-42d3-bb25-58217bf09ea1)

**Comment by fennghuang** [comment]
这个看上去像是 edge 浏览器的功能
password demo 并未做显隐的密码的功能
![image](https://github.com/Tencent/tdesign-mobile-vue/assets/89014758/823f9fa0-1dca-47d4-a521-81d5610e0d73)
