### ISSUE TITLE
[外部样式类] 描述问题的标题

### ISSUE THREAD

**Issue by deajax** [Tencent/tdesign-mobile-vue#1125]
### 这个功能解决了什么问题

可以协同tailwindcss来辅助td框架开发项目

### 你建议的方案是什么

增加类似小程序的externalClasses类，比如：
虽然<t-cell class="custom-class"> 的class可以直接控制cell组件，但是cell的下级如titile，desc等无法直接控制，只能在css里写诸如「.t-cell .t-cell-title { ''' }」这样的，如果使用tailwind的话，可以直接在class定义原子类型来控制下级，就像小程序那样，t-class-title="text-red-600"就可以直接定义到title的class上了，而不用写到css上。

**Comment by anlyyao** [comment]
@deajax 小程序和 vue 机器还是不一样的，小程序外部样式类是为了解决组件开启组件隔离后外部无法修改组件样式，而且是局部的。所以目前暂时不考虑加externalClasses属性，如果目标是修改组件下级样式，可以看一下深度选择器 :deep()。
