### ISSUE TITLE
[t-popup] 在组件上使用class属性和style属性,会有vue警告:Extraneous non-props attributes (class) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 

### ISSUE THREAD

**Issue by leihaoj** [Tencent/tdesign-mobile-vue#1126]
### tdesign-mobile-vue 版本

1.0.5

### 框架版本

3.3.4

### 补充说明

虽然不影响正常使用，但是请问能否解决一下控制台警告问题?文档上也使用了style="padding: 100px",一样会警告
## IssueShoot
- 预估时长: 1
- 期望完成时间: 2023-10-19 00:00:00 +0000 UTC
- 开发难度: 低
- 参与人数: 1
- 需求对接人: anlyyao
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by anlyyao** [comment]
@leihaoj 收到反馈。确实是popup的问题，有多个根节点，导致在组件上添加非props或emits的属性，无法继承组件，导致控制台告警。我这边处理一下～
