### ISSUE TITLE
Progress 进度条颜色渐变无效

### ISSUE THREAD

**Issue by PandaLeo** [Tencent/tdesign-mobile-vue#1128]
### tdesign-mobile-vue 版本

1.0.2

### 重现链接

https://github.com/Tencent/tdesign-mobile-vue/blob/develop/src/progress/type.ts

### 重现步骤

按照文档
  /**
   * 进度条颜色。示例：'#ED7B2F' 或 'orange' 或 `['#f00', '#0ff', '#f0f']` 或 `{ '0%': '#f00', '100%': '#0ff' }` 或  `{ from: '#000', to: '#000' }` 等
   * @default ''
   */
  color?: string | Array<string> | Record<string, string>;
这里的进度条颜色在 `{ '0%': '#f00', '100%': '#0ff' }` 或  `{ from: '#000', to: '#000' }`定义下应该支持渐变色，但是实测只有单色生效

### 期望结果

支持渐变色显示

### Node版本

18.2.0

**Comment by anlyyao** [comment]
@PandaLeo 你在确认一下使用？ 我这边测试提供的示例都能支持到。
```
<t-progress :percentage="80" :color="{ '0%': '#f00', '100%': '#0ff' }" />
<t-progress :percentage="80" :color="{ from: '#f00', to: '#000' }" />
<t-progress :percentage="80" :color="['#f00', '#0ff', '#f0f']" />
```
<img width="357" alt="截屏2023-10-18 11 44 12" src="https://github.com/Tencent/tdesign-mobile-vue/assets/51158141/ba702d58-24e6-48e7-8e4e-f10ec8ba5f70">

**Comment by PandaLeo** [comment]
> @PandaLeo 你在确认一下使用？ 我这边测试提供的示例都能支持到。
> 
> ```
> <t-progress :percentage="80" :color="{ '0%': '#f00', '100%': '#0ff' }" />
> <t-progress :percentage="80" :color="{ from: '#f00', to: '#000' }" />
> <t-progress :percentage="80" :color="['#f00', '#0ff', '#f0f']" />
> ```
> 
> <img alt="截屏2023-10-18 11 44 12" width="357" src="https://user-images.githubusercontent.com/51158141/276077409-ba702d58-24e6-48e7-8e4e-f10ec8ba5f70.png">

@anlyyao 抱歉，我这里写的不够详细，直线进度条是渐变可用的，环形进度条使用渐变色的没有生效

**Comment by anlyyao** [comment]
> :color="{ from: '#f00', to: '#000' }"

环形不支持渐变色。环形是基于 svg circle实现的，里面的渐变色实现有些复杂，需要考虑两种和多种渐变色，目前并不考虑支持嘎～

**Comment by anlyyao** [comment]
> > @PandaLeo 你在确认一下使用？ 我这边测试提供的示例都能支持到。
> > ```
> > <t-progress :percentage="80" :color="{ '0%': '#f00', '100%': '#0ff' }" />
> > <t-progress :percentage="80" :color="{ from: '#f00', to: '#000' }" />
> > <t-progress :percentage="80" :color="['#f00', '#0ff', '#f0f']" />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="截屏2023-10-18 11 44 12" width="357" src="https://user-images.githubusercontent.com/51158141/276077409-ba702d58-24e6-48e7-8e4e-f10ec8ba5f70.png">
> 
> @anlyyao 抱歉，我这里写的不够详细，直线进度条是渐变可用的，环形进度条使用渐变色的没有生效


环形不支持渐变色。环形是基于 svg circle实现的，里面的渐变色实现有些复杂，需要考虑两种和多种渐变色，目前并不考虑支持嘎～
