### ISSUE TITLE
[Collapse] 在Popup等弹出层中高度计算错误

### ISSUE THREAD

**Issue by gushisan** [Tencent/tdesign-mobile-vue#1134]
### tdesign-mobile-vue 版本

1.0.5

### 重现步骤

demo
```vue
<template>
  <t-popup
    v-if="props.visible"
    :visible="props.visible"
    placement="right"
    style="width: 300px"
    @close="onHide"
  >
    <div>
      <t-collapse :value="values" @change="handleChange">
        <t-collapse-panel
          v-for="i in 4"
          :key="i"
          :value="i"
          header="折叠面板标题"
          :disabled="i === 4"
        >
          <div class="content">
            此处可自定义内容此处可自定义内容此处可自定义内容此处可自定义内容此处可自定义内容此处可自定义内容此处可自定义内容此处可自定义内容此处可自定义内容此处可自定义内容此处可自定义内容此处可自定义内容此处可自定义内容此处可自定义内容可自定义内容
          </div>
        </t-collapse-panel>
      </t-collapse>
    </div>
  </t-popup>
</template>
```
当Collapse存在于弹出层中 高度计算存在问题
![image](https://github.com/Tencent/tdesign-mobile-vue/assets/45390335/7c30a494-529d-4faa-ba5d-466e20bbe351)

原因：
源码路径~/src/collapse/collapse-panel.vue
![image](https://github.com/Tencent/tdesign-mobile-vue/assets/45390335/9ee4f336-6ffa-43d9-b6af-e51ea00e0e45)
触发组件onMounted时 外层popup visible为false 所以获取不到高度

### 期望结果

能正确渲染

### 实际结果

无法正确渲染

### 框架版本

Vue(3.3.4)

**Comment by fennghuang** [comment]
@gushisan 按你的 demo 代码 https://stackblitz.com/edit/zknsfi?file=src%2Fdemo.vue 未能复现，可否在此链接基础上再补充一下你的 demo

**Comment by gushisan** [comment]
> @gushisan 按你的 demo 代码 https://stackblitz.com/edit/zknsfi?file=src%2Fdemo.vue 未能复现，可否在此链接基础上再补充一下你的 demo <img alt="image" width="522" src="https://user-images.githubusercontent.com/89014758/277146216-b00f4721-ec29-45d1-a7ef-3558236c10d4.png">

![image](https://github.com/Tencent/tdesign-mobile-vue/assets/45390335/e75840bb-94fa-4fee-b4b5-70690d76c267)
去掉这行即可复现

**Comment by gushisan** [comment]
@fennghuang 这里使用v-if 是为了暂时避免渲染错误的问题 去除即可复现

**Comment by fennghuang** [comment]
@gushisan 已复现，会尽快处理，感谢反馈。
