### ISSUE TITLE
[build] npm run build 报错

### ISSUE THREAD

**Issue by wencongNew** [Tencent/tdesign-mobile-vue#1138]
### tdesign-mobile-vue 版本

dev

### 重现步骤

npm run build
src/**/*.ts, src/**/*.vue, !src/**/demos, !src/**/*.d.ts, !src/**/__tests__, !src/index-lib.ts → es/...
[!] Error: Could not resolve './style/css.js' from src/action-sheet/style/index.js

### 框架版本

3.2

### 浏览器版本

8.2

### 补充说明

npm run build
src/**/*.ts, src/**/*.vue, !src/**/demos, !src/**/*.d.ts, !src/**/__tests__, !src/index-lib.ts → es/...
[!] Error: Could not resolve './style/css.js' from src/action-sheet/style/index.js

**Comment by anlyyao** [comment]
@wencongNew  是直接拉的仓库代码吗？ npm run dev没问题，单独npm run build 有问题？我们的样式文件在子仓库，首次运行需要初始化子仓库。

**Comment by wencongNew** [comment]
![image](https://github.com/Tencent/tdesign-mobile-vue/assets/40652939/e67c004b-036f-411c-b9af-f592eda4e8ba)
已经初始化子仓库了

**Comment by anlyyao** [comment]
@wencongNew 你仓库地址是？

**Comment by mengyaqian** [comment]
请问执行build报错这个是怎么解决的，我有同样的问题
