### ISSUE TITLE
[t-dropdown-item] value属性没有受控，监听不到变化 chang事件也无法触发

### ISSUE THREAD

**Issue by wr1984** [Tencent/tdesign-mobile-vue#114]
### tdesign-mobile-vue 版本

使用最新的0.8.5发现此问题

### 重现步骤

`   

    <t-dropdown-menu>
       <t-dropdown-item v-model="parkType" label="园区类型" :options="parkTypeOptions" @change="handleChange" />
    </t-dropdown-menu>

    const parkType = ref('');
    watch(parkType, (val) => {
      console.log(val);   // 监听不到变化
    });
    
    const handleChange = (val) => {
      console.log(val)  // 监听不到变化
    }
`

### 期望结果

下拉选择后监听到value的值变化

### 实际结果

监听不到value的值变化

### 框架版本

Vue(3.2.25)

### 浏览器版本

Chrome(101.0.4951.54)

### 系统版本

Windows 11

### Node版本

Node(v14.17.6)

**Comment by lookguy** [comment]
> 0.8.6版本修复了吗
