### ISSUE TITLE
[Dialog] 命令行调用方法的Dialog不会销毁

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-mobile-vue#1148]
### tdesign-mobile-vue 版本

1.0.6

### 重现链接

https://stackblitz.com/edit/hnyrgs-macvbr?file=src%2Fpages%2Fdemo.vue

### 重现步骤

命令行调用方法的Dialog不会销毁

1. 示例点击到demo页面，不断的点击命令行操作按钮，每次都会创建一下新的dom，不会销毁

2. 示例点击跳转home和跳转demo的页面跳转中，通过命令行创建的按钮的dom都不会销毁。

3. 在确定弹窗打开的情况下，通过手机端的返回键或浏览器返回时，对话框不会消失。

<img width="792" alt="image" src="https://github.com/Tencent/tdesign-mobile-vue/assets/13745660/e87018d5-fd25-44b0-bcde-c36d097c7157">

### 期望结果

1. 优化命令行调用方法的Dialog的销毁
2. 在弹窗打开的情况下，页面跳转时是否可自动销毁对话框，或提供销毁方法

### 实际结果

1. 每次创建都不会自动销毁弹窗的dom。
2. 弹窗打开的情况下，路由跳转，对话框不会消失。

### 框架版本

Vue(3.2.0)

### 浏览器版本

Chrome(117.0.5938.149)

### 系统版本

MacOS

### Node版本

16.17.0

**Comment by fennghuang** [comment]
感谢反馈
销毁可以使用 `destroyOnClose: true`，但这个属性没有透传过去，我调整一下
