### ISSUE TITLE
[Picker] 能不能支持PC端

### ISSUE THREAD

**Issue by chenshiming1113** [Tencent/tdesign-mobile-vue#1150]
### 这个功能解决了什么问题

平时做一些企业微信自建应用，用户希望手机和PC都可以用。但是tdesign-mobile-vue组件库的Picker不支持PC端选择，PC端滚动不了。如果增加支持PC端会方便很多。希望官方可以考虑。

### 你建议的方案是什么

希望官方可以考虑，不然简单的功能都要手机和PC做两套。特别是企业微信的自建应用基本都是要求手机电脑都能用。

**Comment by fennghuang** [comment]
@chenshiming1113 PC 滚动不了是否可以提供具体的 demo？
这个 demo 上 https://tdesign.tencent.com/mobile-vue/mobile.html#/picker 在PC上鼠标无法拖动？
另，请提供下具体的浏览器版本、操作系统

**Comment by chenshiming1113** [comment]
官方demo是正常的，但是在PC端企业微信滚动不了。会不会是企业微信的浏览器不兼容导致的？

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年11月6日 14:57
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Tencent/tdesign-mobile-vue] [Picker] 能不能支持PC端 (Issue #1150)


@chenshiming1113<https://github.com/chenshiming1113> PC 滚动不了是否可以提供具体的 demo？
这个 demo 上 https://tdesign.tencent.com/mobile-vue/mobile.html#/picker 在PC上鼠标无法拖动？
另，请提供下具体的浏览器版本、操作系统

―

**Comment by fennghuang** [comment]
@chenshiming1113 我这里 mac 电脑，企业微信版本 版本 4.1.10.90765，使用企业微信内置浏览器，打开 demo，picker 可以拖拽。
手边暂时没有 win 本，我得找找

**Comment by chenshiming1113** [comment]
刚试了，官方demo是可以的，应该是我用的方式哪里不对。非常感谢！

**Comment by chenshiming1113** [comment]
试了下，还是不行。但是官方的demo网址可以。不知道是哪里问题。我拷贝的官方文档的代码。是不是官方demo网站做了特殊的处理？
![Uploading 本地demo.png…]()
![Uploading 官方demo.png…]()

**Comment by chenshiming1113** [comment]
试了下，还是不行，我就只用了这一个库。但是官方的demo网址可以。不知道是哪里问题。我拷贝的官方文档的代码。是不是官方demo网站做了特殊的处理？

**Comment by fennghuang** [comment]
@chenshiming1113 请提供一下你执行的代码，方便的话，提供一下录屏。官网 demo 未作特殊处理的

**Comment by chenshiming1113** [comment]
我在官方demo网站点 “查看页面源代码”，发现官方demo网页多了这个脚本：
<script>
!function(a){var b=a.createElement("script");b.onload=function(){TouchEmulator();},b.src="https://tdesign.gtimg.com/js/touch-emulator.js",a.body.appendChild(b)}(document);
</script>
我加上这段<script>，就可以了。

**Comment by chenshiming1113** [comment]
我在官方demo网站点 “查看页面源代码”，发现官方demo网页多了这个脚本：

<script>
 !function(a){var b=a.createElement("script");b.onload=function(){TouchEmulator();},b.src="https://tdesign.gtimg.com/js/touch-emulator.js",a.body.appendChild(b)}(document); </script>


我加上这段<script>，就可以了。

________________________________
发件人: fennghuang ***@***.***>
发送时间: 2023年11月6日 16:53
收件人: Tencent/tdesign-mobile-vue ***@***.***>
抄送: chenshiming1113 ***@***.***>; Mention ***@***.***>
主题: Re: [Tencent/tdesign-mobile-vue] [Picker] 能不能支持PC端 (Issue #1150)


@chenshiming1113<https://github.com/chenshiming1113> 请提供一下你执行的代码，方便的话，提供一下录屏。官网 demo 未作特殊处理的

―

**Comment by ChenXiaoMian** [comment]
> 我在官方demo网站点 “查看页面源代码”，发现官方demo网页多了这个脚本：
> 
> <script>
>  !function(a){var b=a.createElement("script");b.onload=function(){TouchEmulator();},b.src="https://tdesign.gtimg.com/js/touch-emulator.js",a.body.appendChild(b)}(document); </script>
> 
> 
> 我加上这段<script>，就可以了。
> […](#)

@chenshiming1113 这个解决了picker组件在pc端使用，但是又出现了input组件在pc端不能输入的问题，搜索了一下 发现 touch-emulator 的库，换个地址能解决（[https://github.com/hammerjs/touchemulator/blob/master/touch-emulator.js](https://github.com/hammerjs/touchemulator/blob/master/touch-emulator.js)），发现原来的库里有[忽略某些标签](https://github.com/hammerjs/touchemulator?tab=readme-ov-file#touchemulatorignoretags--)，代码抄了一半 😂😂
