### ISSUE TITLE
[Dialog] $dialog方法报错，返回的DialogInstance没有hide,show等方法

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-mobile-vue#1151]
### tdesign-mobile-vue 版本

1.0.6

### 重现链接

https://stackblitz.com/edit/y75h2d-vkqxff?file=src%2Fdemo.vue

### 重现步骤

![image](https://github.com/Tencent/tdesign-mobile-vue/assets/13745660/c5e75e93-2388-4c1c-afc2-f094e1ad96d5)

使用$dialog报错$dialog is not a function

使用$dialog.confirm 和 $dialog.alert返回的 dialogInstance中没有destroy,  show, hide, update方法

### 期望结果

希望可以提供$dialog和dialogInstance相关的方法

### 实际结果

目前按文档使用报错

### 框架版本

Vue(3.2.0)

### 浏览器版本

Chrome(117.0.5938.149)

### 系统版本

MacOS

### Node版本

16.17.0

**Comment by fennghuang** [comment]
感谢反馈，已定位到相关问题，回尽快修复
