### ISSUE TITLE
Cascader 能不能考虑支持选择任意层级，而不是只能选择最后一级

### ISSUE THREAD

**Issue by chenshiming1113** [Tencent/tdesign-mobile-vue#1156]
### 这个功能解决了什么问题

手机端选择部门时，不一定只选择最后一层级部门，比如部门一共有4级，可能选择二级或三级部门。

### 你建议的方案是什么

希望考虑像PC端的Cascader 可以选择任意层级，点确定按钮则选择选择结束
## IssueShoot
- 预估时长: 1
- 期望完成时间: 2023-11-30
- 开发难度: 低
- 参与人数: 1
- 需求对接人: anlyyao
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by anlyyao** [comment]
@chenshiming1113 可以支持点击确认按钮后结束选择。 但是你说的“不一定只选择最后一层级部门，比如部门一共有4级，可能选择二级或三级部门”，不是很理解，有具体和PC哪一个示例对应吗？

**Comment by chenshiming1113** [comment]
https://tdesign.tencent.com/vue/components/cascader#%E9%80%89%E6%8B%A9%E4%BB%BB%E6%84%8F%E4%B8%80%E9%A1%B9%E7%9A%84%E7%BA%A7%E8%81%94%E9%80%89%E6%8B%A9%E5%99%A8
