### ISSUE TITLE
[Picker] 滑动下拉选项不顺畅，会跳上跳下，特别在手机上

### ISSUE THREAD

**Issue by chenshiming1113** [Tencent/tdesign-mobile-vue#1157]
### tdesign-mobile-vue 版本

1.0.6

### 重现链接

https://tdesign.tencent.com/mobile-vue/components/picker

### 重现步骤

从最开始版本一直有这个问题，影响使用体验。滑动选项一点不顺畅，特别手机上，跳来跳去。

### 期望结果

可以参考其他ui库，vant，nutui那样平滑的滑动。t-design比这些库美观好看，这也是我选择t-design的重要原因

**Comment by anlyyao** [comment]
@chenshiming1113 请提供可复现的手机型号、浏览器版本，方便的话可以提供录屏
