### ISSUE TITLE
[DropdownMenu] 使用ref动态数据时候，设置value，label不显示

### ISSUE THREAD

**Issue by thirteenlee** [Tencent/tdesign-mobile-vue#1158]
### tdesign-mobile-vue 版本

1.06

## IssueShoot
- 预估时长: 5
- 期望完成时间: 2024-04-26 00:00:00 +0000 UTC
- 开发难度: 中
- 参与人数: 1
- 需求对接人: anlyyao
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by anlyyao** [comment]
@thirteenlee 辛苦提供一下可复现代码片段，我记得这个问题有修复来着～

**Comment by anlyyao** [comment]
任务目标：

- sfc 改 tsx
- 验证问题是否还存在
