### ISSUE TITLE
[SwipeCell] 收回单元格时存在卡顿

### ISSUE THREAD

**Issue by imyeyu** [Tencent/tdesign-mobile-vue#1167]
### tdesign-mobile-vue 版本

1.0.7

### 重现链接

https://tdesign.tencent.com/mobile-vue/mobile.html#/swipe-cell

### 重现步骤

官方文档的示例也存在这个问题

![](https://raw.githubusercontent.com/imyeyu/imgbed/main/20231127124511%20.gif)

### 框架版本

3.3.4

### 浏览器版本

Edge(119.0.2151.72)

### 系统版本

Windows10

### Node版本

18.15.0

## IssueShoot
- 预估时长: 3
- 期望完成时间: 2023-12-04
- 开发难度: 中
- 参与人数: 1
- 需求对接人: anlyyao
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by yaogengzhu** [comment]
@imyeyu  hello  这个在真机的情况下有异常表现吗？ 我验证了下 iPhone12 、小米11 的情况下都表现良好，挺流畅的

**Comment by imyeyu** [comment]
> @imyeyu hello 这个在真机的情况下有异常表现吗？ 我验证了下 iPhone12 、小米11 的情况下都表现良好，挺流畅的

现在 1.0.10 在 iPhoneSE2 和 iPhone13 下表现正常
