### ISSUE TITLE
Cascader的options为什么用响应式值从网络上获取值之后一直是空

### ISSUE THREAD

**Issue by zfw3842415** [Tencent/tdesign-mobile-vue#1173]
### tdesign-mobile-vue 版本

1.0.6

## IssueShoot
- 预估时长: 8
- 期望完成时间: 2024-06-21 00:00:00 +0000 UTC
- 开发难度: 高
- 参与人数: 1
- 需求对接人: anlyyao
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by anlyyao** [comment]
有可复现地址吗？ 我记得caascader有提供一个异步加载数据的示例

**Comment by zfw3842415** [comment]
现在的方法是微信群里 陈宇扬 提供的在上面添加一个:key
<img width="304" alt="d5467f4b1cbd59ae3dfe73d4d85b606" src="https://github.com/Tencent/tdesign-mobile-vue/assets/8286690/460eca14-d221-4b75-bab5-2efa82aed630">

**Comment by zhoudad** [comment]
微信群可以给我一个吗，这个问题给我整崩溃了，一度怀疑我的写法有问题

**Comment by anlyyao** [comment]
任务目标：
1. sfc 改 tsx
2. 验证问题是否还存在

**Comment by KYSpring** [comment]
I am trying to resolve this issue

**Comment by anlyyao** [comment]
# 1344

**Comment by rico0808** [comment]
v1.2.3 该问题依然存在。:options="cascadeOptions" 只有cascadeOptions初始值生效，后续修改 cascadeOptions 都没有生效。使用 :key="cascadeOptions.length" 暂时解决。

**Comment by lnbiuc** [comment]
> v1.2.3 该问题依然存在。:options="cascadeOptions" 只有cascadeOptions初始值生效，后续修改 cascadeOptions 都没有生效。使用 :key="cascadeOptions.length" 暂时解决。

可以解决，但是重新渲染会导致弹出的动画失效

**Comment by lnbiuc** [comment]
v1.2.4存在同样的问题

**Comment by anlyyao** [comment]
我来跟进看看～

本周的版本无法带上了，预计节后第一个版本可带
