### ISSUE TITLE
[DateTimePicker] 移动端的组件无法通过鼠标滑动选择

### ISSUE THREAD

**Issue by nicolastinger** [Tencent/tdesign-mobile-vue#1187]
### 这个功能解决了什么问题

![1702609255644](https://github.com/Tencent/tdesign-mobile-vue/assets/61414972/b99dd7b5-ff04-4619-a4e4-eb6935a06a9d)

### 你建议的方案是什么

增加鼠标滑动选择日期功能

**Comment by anlyyao** [comment]
移动端只有touch哦~

**Comment by anlyyao** [comment]
-
