### ISSUE TITLE
[Upload] 没有 “拉起拍照” 的功能

### ISSUE THREAD

**Issue by joker-duzhong** [Tencent/tdesign-mobile-vue#1190]
### 这个功能解决了什么问题

在常见的填入图片的场景中， 通常包含相册选择和拍照上传， 标题中写了 
![image](https://github.com/Tencent/tdesign-mobile-vue/assets/55167916/651ec470-ee7c-47c2-98a7-fb4457b356ee)
，但我没有在文档中找到打开的方式，是否有计划完善此功能

### 你建议的方案是什么

完善此功能

**Comment by anlyyao** [comment]
@joker-duzhong 点击上传 就有“拍摄”和“从相册中选择”选项
