### ISSUE TITLE
[swipe-cell] 演示完全是不动的

### ISSUE THREAD

**Issue by wanghaisheng** [Tencent/tdesign-mobile-vue#1194]
### tdesign-mobile-vue 版本

https://tdesign.tencent.com/mobile-vue/components/swipe-cell

### 重现步骤

windows 11 edge浏览器
打开以后
不止这个组件，下拉刷新也是下拉不了的
 https://tdesign.tencent.com/mobile-vue/components/pull-down-refresh

**Comment by anlyyao** [comment]
@wanghaisheng 这个是H5，建议使用手机扫码体验～

**Comment by wanghaisheng** [comment]
你是说手机浏览器打开链接吗还是说url转二维码 微信扫码@anlyyao

**Comment by anlyyao** [comment]
> 你是说手机浏览器打开链接吗还是说url转二维码 微信扫码@anlyyao

微信扫码，如果硬要pc预览，用这个地址https://tdesign.tencent.com/mobile-vue/mobile.html#/swipe-cell， 切到手机端

**Comment by wanghaisheng** [comment]
感觉这个可以补到文档里，方便我这些小白上手
