### ISSUE TITLE
[Picker 选择器] t-cascade无法绑定动态数据

### ISSUE THREAD

**Issue by jevons-lee-w** [Tencent/tdesign-mobile-vue#1205]
### tdesign-mobile-vue 版本

1.0.9

### 重现步骤

t-cascade只能绑定静态数据，若初始绑定ref([])，网络请求成功后重设数据源，则只能展示一列数据。若初始绑定[{"label":"","value":"","children":[]}]格式的假数据，重设数据源后，样式上呈现2列，但右侧为空白。感觉上Picker并不能正确取到children数据。此外，我用div动态绑定展示children，页面上可以正常显示真实的网络数据。

**Comment by anlyyao** [comment]
Duplicate of #1173
