### ISSUE TITLE
[picker] 初始化滚动参数，itemHeight写死了40，不能根据样式设置的高度来定义。

### ISSUE THREAD

**Issue by MMZiLi0514** [Tencent/tdesign-mobile-vue#1207]
### tdesign-mobile-vue 版本

1.0.9

### 重现步骤

样式全局定义为50px
:root {
  --td-picker-item-height: 50px;
}
滚动定位出现偏差
![screenshot-20240112-180140](https://github.com/Tencent/tdesign-mobile-vue/assets/20982605/3b3dd24a-f9b2-4acb-8b92-eb6767c08344)

**Comment by fennghuang** [comment]
感谢反馈 这个问题我看下
