### ISSUE TITLE
t-cascader 中的theme在tab状态下显示异常

### ISSUE THREAD

**Issue by StanleyLZH** [Tencent/tdesign-mobile-vue#1208]
### tdesign-mobile-vue 版本

最新发布版本

**Comment by anlyyao** [comment]
@StanleyLZH  感谢反馈🙏，已知问题已处理完毕，本周版本会带上～

**Comment by anlyyao** [comment]
> @StanleyLZH 感谢反馈🙏，已知问题已处理完毕，本周版本会带上～

已处理在1.0.10版
