### ISSUE TITLE
[CountDown] 标签页置于后台，倒计时停止

### ISSUE THREAD

**Issue by RomenMark** [Tencent/tdesign-mobile-vue#1213]
### tdesign-mobile-vue 版本

1.0.9

### 期望结果

标签页置于后台，倒计时正常进行

### 框架版本

vue3

### Node版本

18.19.0

## IssueShoot
- 预估时长: 3
- 期望完成时间: 2024-10-25 00:00:00 +0000 UTC
- 开发难度: 中
- 参与人数: 1
- 需求对接人: anlyyao
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by anlyyao** [comment]
@RomenMark 贴一下可复现代码片段和实际场景

**Comment by hkaikai** [comment]
已认领
