### ISSUE TITLE
[TDesign mobile-vue 官网] 大量图片&资源文件存在404现象

### ISSUE THREAD

**Issue by ctyytc** [Tencent/tdesign-mobile-vue#1214]
### tdesign-mobile-vue 版本

1.0.10

### 重现链接

https://tdesign.tencent.com/mobile-vue/components/swiper

### 重现步骤

PC浏览器打开[Swiper](https://tdesign.tencent.com/mobile-vue/components/swiper)组件文档页面，可以看到示例图片是404状态

### 期望结果

图片展示正常

### 实际结果

图片资源404

### 补充说明

除了Swiper组件，还有很多其它页面也存在相似问题，例如[关于](https://tdesign.tencent.com/about/introduce)

**Comment by ctyytc** [comment]
同时，官网上的“企业微信群”二维码，扫码后显示系统不可用，也是一个问题

**Comment by anlyyao** [comment]
> 同时，官网上的“企业微信群”二维码，扫码后显示系统不可用，也是一个问题

收到，设计指南部分图片资源已恢复，示例图片资源正在恢复中。[官网企业微信群二维码](https://tdesign.tencent.com/mobile-vue/overview) 我这边验证没有问题呀～

**Comment by anlyyao** [comment]
已处理～
