### ISSUE TITLE
[Tabs] 按需引入Tabs控制台警告 Failed to resolve component: t-badge

### ISSUE THREAD

**Issue by Delevin888** [Tencent/tdesign-mobile-vue#1218]
### tdesign-mobile-vue 版本

1.0.10

### 重现步骤

![image](https://github.com/Tencent/tdesign-mobile-vue/assets/38110513/087cff13-2552-4d7b-a4cf-b0efaac3905f)

### 期望结果

控制台无警告

### 实际结果

控制台警告

### 框架版本

Vue(3.4.15)

### 浏览器版本

Chrome(120.0.0.0)

### 系统版本

Windows(11)

### Node版本

18.18.2

**Comment by zhouxhere** [comment]
solved in #1239
