### ISSUE TITLE
[Toast] 组件希望提供duration 0秒

### ISSUE THREAD

**Issue by kiter** [Tencent/tdesign-mobile-vue#1221]
### 这个功能解决了什么问题

解决需要长时间等待后台服务或者其它服务的依赖，再手动调用toast.clear 来关闭这个提示。

### 你建议的方案是什么

duration 改为0秒，现在传超长时间也会有问题。
## IssueShoot
- 预估时长: 3
- 期望完成时间: 2024-11-26 00:00:00 +0000 UTC
- 开发难度: 中
- 参与人数: 1
- 需求对接人: anlyyao
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by anlyyao** [comment]
方案：优化 durantion 属性， 表示弹窗显示毫秒数长，值为 0 表示永久显示。

**Comment by novlan1** [comment]
现在已经是了
