### ISSUE TITLE
[Cascader 级联选择器] 输出异步加载文档

### ISSUE THREAD

**Issue by synctimes163** [Tencent/tdesign-mobile-vue#1226]
### 这个功能解决了什么问题

[Cascader 级联选择器] 输出异步加载文档示例，有利于快速实现异步加载示例

### 你建议的方案是什么

![image](https://github.com/Tencent/tdesign-mobile-vue/assets/78259973/571e8082-75b9-40d4-b4ab-40fb6e624a36)
提供异步加载示例代码，完善api 异步加载文档说明

**Comment by anlyyao** [comment]
@synctimes163  先看一下一下源码哈～ https://github.com/Tencent/tdesign-mobile-vue/blob/develop/src/cascader/demos/lazy.vue

**Comment by synctimes163** [comment]
> @synctimes163 先看一下一下源码哈～ https://github.com/Tencent/tdesign-mobile-vue/blob/develop/src/cascader/demos/lazy.vue

感谢哈，实现了
