### ISSUE TITLE
[Upload 上传] autoUpload 设置 false，无法触发自定义 requestMethod 参数

### ISSUE THREAD

**Issue by synctimes163** [Tencent/tdesign-mobile-vue#1228]
### tdesign-mobile-vue 版本

^1.0.15

### 重现步骤

<template>
	<div class="upload-demo"> 
		<t-upload :autoUpload="autoUpload" v-model="files"  :max="10"  :request-method="requestMethod" :grid-config="gridConfig" :action="action" :on-fail="onFail"
			:on-progress="onProgress" :on-change="onChange" :on-preview="onPreview" :on-success="onSuccess"
			:on-remove="onRemove" :on-select-change="onSelectChange" :on-click-upload="onClickUpload">
		</t-upload>
	</div>
</template>

<script>
	export default {
		name: 'Upload',
		props: {
			// files: {
			// 	type: Array,
			// 	default: []
			// },
			gridConfig: {
				type: Number,
				default: 1
			},
			action: {
				type: String,
				default: ""
			},
			autoUpload: {
				type: Boolean,
				default: false
			},
		},
		computed: {
		  requestMethod(value) {
			console.log(":requestMethod", value)
		  }
		},
		data(){
			
			return {
				files: []
			}
			
		},
		methods: {
			onFail(res) {
				console.log("onFail res=>", res)
			},
			onProgress(res) {
				console.log("onProgress res=>", res)
			},
			onChange(value, context) {
				console.log("onChange value=>", value)
				console.log("onChange context=>", context)
			
				// this.files = res
				
				// context.onSuccess(value, context)

				console.log("context.response", context.response)
				console.log("context.context", Object.keys(context) )
				
				
			},
			onPreview(res) {
				console.log("onPreview res=>", res)
			},
			onSuccess(res) {
				console.log("onSuccess res=>", res)
			},
			onRemove(res) {
				console.log("onRemove res=>", res)
			},
			onSelectChange(res) {
				console.log("onSelectChange res=>", res)
			},
			onClickUpload(res) {
				console.log("onClickUpload res=>", res)
			},
	// 		requestMethod(res) {
	// 			console.log("requestMethod res=>", res)
				
	// 			return new Promise((resolve)=>{
	// 				resolve({
	// 					status:"success",
	// 					response: {
	// 						url:"https://tdesign.gtimg.com/site/avatar.jpg"
	// 					}
	// 				})
	// 			})
		
				
			
	
	// 		},
		}
	}
</script>

<style scoped lang="scss">
	h3 {
		margin: 40px 0 0;
	}

	ul {
		list-style-type: none;
		padding: 0;
	}

	li {
		display: inline-block;
		margin: 0 10px;
	}

	a {
		color: #42b983;
	}
</style>
![79a851a1ba60987261c87d04e942740](https://github.com/Tencent/tdesign-mobile-vue/assets/78259973/744b5e81-8256-45f5-830b-86b0bd825552)

### 期望结果

requestMethod 触发生效，提供 自定义上传 DEMO 到文档种

**Comment by synctimes163** [comment]
@fayching

**Comment by anlyyao** [comment]
@synctimes163 requestMethod这里是和PC对齐的，写法可以先参考一下PC。  https://tdesign.tencent.com/vue-next/components/upload?tab=demo
