### ISSUE TITLE
[PullDownRefresh 下拉刷新] 结合Tabs 选项卡 触底会触发多次

### ISSUE THREAD

**Issue by synctimes163** [Tencent/tdesign-mobile-vue#1237]
### tdesign-mobile-vue 版本

1.0.10

### 重现步骤

![image](https://github.com/Tencent/tdesign-mobile-vue/assets/78259973/65e6a276-9cf2-437f-81f8-5bf7c6fd0734)

每次触底要下拉到底部，再往上拉一下才触发，而且结合 tabs 组件形式还会触发多次

### 期望结果

下拉到底部立马触发，而不是再往上一下才触发

**Comment by anlyyao** [comment]
Duplicate of #992
