### ISSUE TITLE
[t-tabs] Vue使用该组件，设置最大宽，后，sticky-props 样式错位了。

### ISSUE THREAD

**Issue by synctimes163** [Tencent/tdesign-mobile-vue#1298]
### tdesign-mobile-vue 版本

1.1.1

### 重现步骤

![image](https://github.com/Tencent/tdesign-mobile-vue/assets/78259973/9dec272e-30e8-48af-84f3-d798e2d2544a)
#app {
		font-family: Avenir, Helvetica, Arial, sans-serif;
		-webkit-font-smoothing: antialiased;
		-moz-osx-font-smoothing: grayscale;
		max-width: 500px;
		margin: 0 auto;
	}

![image](https://github.com/Tencent/tdesign-mobile-vue/assets/78259973/d98aee4f-b5ea-4bed-8152-14a044aec825)

### 期望结果

全局设置最大宽后，样式正常

**Comment by synctimes163** [comment]
.t-sticky__content 设置 最大值才能兼容，能否自适应
`.t-sticky__content {
		max-width: 500px;
		margin: 0 auto;
	}`

**Comment by anlyyao** [comment]
@synctimes163 我没能直接复现， 有直接可复现的仓库之类吗？
