### ISSUE TITLE
[Drawer] 官方示例中带图标的抽屉没有显示图标

### ISSUE THREAD

**Issue by Calvest** [Tencent/tdesign-mobile-vue#130]
### tdesign-mobile-vue 版本

0.8.5

### 重现步骤

Drawer 组件中图标没有正确显示

### 期望结果

显示图标

### 实际结果

没有显示图标

### 框架版本

Vue(3.2.33)

### 浏览器版本

Chrome(102.0.5005.61)

### 系统版本

MacOS(12.4)

### Node版本

17.6.0

**Comment by LeeJim** [comment]
已于 0.9.0 发布
