### ISSUE TITLE
[table] title 传入function 没有生效，还是按照string 方式渲染的

### ISSUE THREAD

**Issue by guoxiaoyi** [Tencent/tdesign-mobile-vue#1340]
### tdesign-mobile-vue 版本

1.2。0

### 重现步骤

      columns: [
        { colKey: 'label', title: '时间', align: 'center', ellipsis: true },
        { colKey: 'items[0].num', title: (h, { col, row }) => row[colKey], align: 'center', ellipsis: true },
      ],

### 期望结果

title 应该是执行这个方法

### 实际结果

(h, { col, row }) => row[colKey]

## IssueShoot
- 预估时长: 8
- 期望完成时间: 2024-05-03 00:00:00 +0000 UTC
- 开发难度: 中
- 参与人数: 1
- 需求对接人: anlyyao
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by anlyyao** [comment]
任务目标：

- sfc 改 tsx
- 验证问题是否还存在
