### ISSUE TITLE
[Cascader] v-model:value动态赋值不生效

### ISSUE THREAD

**Issue by zhujie948** [Tencent/tdesign-mobile-vue#1341]
### tdesign-mobile-vue 版本

1.2.0

### 重现链接

https://stackblitz.com/edit/swujsr-eu37rx?file=src%2Fdemo.vue

### 重现步骤

在弹出选择器showCascader方法中，重新赋值address.value

### 期望结果

Cascader选择器自动回填

### 实际结果

v-model:value未响应

## IssueShoot
- 预估时长: 3
- 期望完成时间: 2024-05-03 00:00:00 +0000 UTC
- 开发难度: 中
- 参与人数: 1
- 需求对接人: anlyyao
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by anlyyao** [comment]
任务目标：

- sfc 改 tsx
- 验证问题是否还存在

**Comment by anlyyao** [comment]
Duplicate of #1173

**Comment by zhujie948** [comment]
https://stackblitz.com/edit/bsmfbb?file=src%2Fdemo.vue
选择器还是没有选中，新赋值的value
