### ISSUE TITLE
[Dialog] inject方式导入在按需引入中无效

### ISSUE THREAD

**Issue by anlyyao** [Tencent/tdesign-mobile-vue#1387]
### tdesign-mobile-vue 版本

最新版

### 重现链接

const $dialog: any = inject('$dialog')
 $dialog.confirm({
        title: '标题',
        content: '内容',
        confirmBtn: '确认'
      })

控制台报错：TypeError: Cannot read properties of undefined (reading 'confirm')
_No response_

**Comment by anlyyao** [comment]
本地测试了官网给出的三种按需引入方式，inject 都能正常使用，未能复现该问题。 如果后续有用户出现类似问题，欢迎重新开贴讨论～

**Comment by GAtomis** [comment]
> ### tdesign-mobile-vue 版本
> 最新版
> 
> ### 重现链接
> const $dialog: any = inject('$dialog') $dialog.confirm({ title: '标题', content: '内容', confirmBtn: '确认' })
> 
> 控制台报错：TypeError: Cannot read properties of undefined (reading 'confirm') _No response_
> 
> ### 重现步骤
> _No response_
> 
> ### 期望结果
> _No response_
> 
> ### 实际结果
> _No response_
> 
> ### 框架版本
> _No response_
> 
> ### 浏览器版本
> _No response_
> 
> ### 系统版本
> _No response_
> 
> ### Node版本
> _No response_
> 
> ### 补充说明
> _No response_

别用按需插件引用，直接手动引入
<img width="871" alt="image" src="https://github.com/user-attachments/assets/56385e39-0355-4ac1-b671-749e276e238a">
