### ISSUE TITLE
[Cell 单元格] 点击报错hover的ctx报错

### ISSUE THREAD

**Issue by nicolastinger** [Tencent/tdesign-mobile-vue#1389]
### tdesign-mobile-vue 版本

"tdesign-mobile-vue": "^1.1.1"

### 重现步骤

<t-cell title="单行标题" arrow hover />在f12设备模拟，移动端的时候，点击即报错。
Uncaught TypeError: Cannot read properties of undefined (reading 'ctx')
    at el.addEventListener.capture [(hover.js:16:1)[](url)](![微信图片_20240510100746](https://github.com/Tencent/tdesign-mobile-vue/assets/61414972/82e2127e-4955-4133-b895-d763ab713e68))
![微信图片_20240510100803](https://github.com/Tencent/tdesign-mobile-vue/assets/61414972/77a81ba1-75fb-437b-b467-35e3c388c961)

### 期望结果

增加这个ctx的null检查

### 框架版本

"vue": "3.2.26",

### 浏览器版本

Microsoft Edge 版本 124.0.2478.80

### 系统版本

win11

### Node版本

v18.16.1

**Comment by anlyyao** [comment]
@nicolastinger 升级版本试试呢？ 我目前看最新的没有这个问题 https://tdesign.tencent.com/mobile-vue/mobile.html#/cell
