### ISSUE TITLE
[t-search] 搜索输入内容，右侧出现两个X

### ISSUE THREAD

**Issue by 1943715762** [Tencent/tdesign-mobile-vue#1390]
### tdesign-mobile-vue 版本

复现

### 重现步骤

把官网案例拿过来，就出现这个问题（代码：
<t-search v-model="keyword" :clearable="true" shape="round" placeholder="请输入关键词搜索" @search="filterList"
				@submit="filterList" @clear="filterList"></t-search>
）
![1715246406430](https://github.com/Tencent/tdesign-mobile-vue/assets/55580893/ea41520e-52f5-4567-aa6f-f75f3d69cebb)

设置clearable为false时候，也有x
![2](https://github.com/Tencent/tdesign-mobile-vue/assets/55580893/66112314-45d8-452e-9cca-74290bac469b)

### 期望结果

去掉第一个x。只保留第二个   圈X

### 实际结果

两个x

### 框架版本

3.2.47

### 浏览器版本

 124.0.6367.119

### 系统版本

window11

### Node版本

16.15.1

### 补充说明

uview3的框架，用tdesign 的ui。把官网search案例拿来就出现这个问题。官网上没问题。不知道咋回事

**Comment by liweijie0812** [comment]
tdesign-mobile-vue 版本升级了吗，[1.0.0-rc.2](https://github.com/Tencent/tdesign-mobile-vue/releases/tag/1.0.0-rc.2 ) 已修复了该问题

**Comment by 1943715762** [comment]
> tdesign-mobile-vue 版本升级了吗，[1.0.0-rc.2](https://github.com/Tencent/tdesign-mobile-vue/releases/tag/1.0.0-rc.2) 已修复了该问题

现在是1.2.0版本，最新版

**Comment by anlyyao** [comment]
@1943715762 这边测试没有发现问题哦， https://stackblitz.com/edit/ezy6rb?file=src%2Fdemo.vue
效果：
<img width="1493" alt="截屏2024-10-16 15 40 42" src="https://github.com/user-attachments/assets/55938907-3e3d-4614-96a5-5ec16f46df83">

或者提供一下你那边完整可复现的项目仓库地址，我们再进一步排查～
