### ISSUE TITLE
[Config] 暗黑模式？自定义主题？

### ISSUE THREAD

**Issue by momtboy** [Tencent/tdesign-mobile-vue#1400]
### 这个功能解决了什么问题

希望能对齐到pc vue-next, 现在移动端的组件库感觉没有人维护。。。

### 你建议的方案是什么

希望能对齐到pc vue-next，支持暗黑模式，支持自定义主题模式

**Comment by anlyyao** [comment]
@momtboy sorry～ 看到的有点晚。已修复基本功能的使用问题，自定义主题方式与pc端保持一致。官网主题生成器预计明年才有时间接入，感兴趣的话可以持续关注～
