### ISSUE TITLE
[下拉树型控件] 在移动端里引入tdesign的pc框架，样式冲突

### ISSUE THREAD

**Issue by 1943715762** [Tencent/tdesign-mobile-vue#1402]
### tdesign-mobile-vue 版本

1.2.0

### 重现步骤

![1716182435024](https://github.com/Tencent/tdesign-mobile-vue/assets/55580893/333d04b4-84f9-4370-ad00-7bd9cb445732)
![1](https://github.com/Tencent/tdesign-mobile-vue/assets/55580893/8e4ee827-cae4-4843-9914-3df6a610fa1d)
想用下tdesign的下拉树，结果导致别的样式乱了，有啥办法解决吗？这俩真的不能同时用吗？
import { TreeSelect } from 'tdesign-vue-next'; 
只要引入这个，就冲突

### 期望结果

如上

### 实际结果

如上

### 系统版本

window11

**Comment by anlyyao** [comment]
@1943715762 可以通过修改pc端的classPrefix来避免个移动端同名组件的样式冲突
