### ISSUE TITLE
[Swiper] 滑动切换的那一刻很不流畅

### ISSUE THREAD

**Issue by ry0513** [Tencent/tdesign-mobile-vue#1405]
### tdesign-mobile-vue 版本

1.2.2

### 重现链接

https://tdesign.tencent.com/mobile-vue/components/swiper?tab=demo

### 重现步骤

手机微信扫描右侧二维码在手机上预览，滑动，很明显的会感觉在不流畅，会突然变化

### 期望结果

希望流畅一些

### 实际结果

https://github.com/Tencent/tdesign-mobile-vue/assets/44745967/9e0e0940-9ba1-4260-a50c-8bc5b40897d4

**Comment by anlyyao** [comment]
@ry0513 中间有修复，可以试试1.2.4版本～
