### ISSUE TITLE
[Toast] 能否支持修改不同theme下的样式

### ISSUE THREAD

**Issue by evy-u** [Tencent/tdesign-mobile-vue#1430]
### tdesign-mobile-vue 版本

1.2.0

### 重现步骤

1. 官方API没有提供自定义主题下的样式修改（包括但不限于背景色，文字色）
2. 想使用样式覆盖的方案，发现theme有值和无值时，t-toast的类名表现一样，无法做出区分

### 期望结果

期望API支持自定义样式

**Comment by anlyyao** [comment]
@evy-u 收到反馈~，前置背景是设计上 theme 主题只与图标关联，不和基础样式挂钩，因此开发时没有额外提供类似`t-toast--${theme}`的 className，考虑到你这个场景，我们讨论一下是新增 theme 相关类名，还是新增 class props
