### ISSUE TITLE
[Swiper] 文字swiper-item加载后文字重叠

### ISSUE THREAD

**Issue by HouEngineer** [Tencent/tdesign-mobile-vue#1431]
### tdesign-mobile-vue 版本

1.2.3

### 重现链接

https://github.com/HouEngineer/issue-tdesign-mobile-vue

### 重现步骤

1. 下载github代码
2. npm install
3. npm run dev
4. 打开链接 http://localhost:5173/swiper

### 期望结果

Swiper加载竖向文字不重叠（没有滑动之前）

### 实际结果

Swiper加载竖向文字没有滑动之前内容重叠

### 框架版本

Vue(3.4.21)

### 浏览器版本

Chrome(125.0.6422.142 (Official Build) (64-bit))

### 系统版本

Windows(Windows 11 Enterprise 23H2)

### Node版本

Node(v20.9.0)

**Comment by anlyyao** [comment]
@HouEngineer 应该已经修复了，处理在 #1404 可以拉源码仓库本地验证。本周发版本会带上～
