### ISSUE TITLE
Message Component 的 onLinkClick 是否有bug？

### ISSUE THREAD

**Issue by lilj** [Tencent/tdesign-mobile-vue#1443]
https://github.com/Tencent/tdesign-mobile-vue/blob/1665eebe814562982a51f1c331f0fad3b6fe5451/src/message/message.vue#L219

为何不是 props.onLinkClick?.(e);

**Comment by anlyyao** [comment]
@lilj  `props.onLinkClick?.({ e });`  是正确的，和文档中的TS 类型`(context: { e: MouseEvent }) => void `是匹配的哈
