### ISSUE TITLE
表格在缩放状态下，文字露出，滚动时，文字抖动

### ISSUE THREAD

**Issue by codeflyA** [Tencent/tdesign-mobile-vue#1462]
### tdesign-mobile-vue 版本

最新版本1.2.4 官网能复现

### 重现链接

https://tdesign.tencent.com/mobile-vue/components/table

### 重现步骤

表格在缩放状态下，文字露出，滚动时，文字抖动
反复实测
在缩放状态下 
![image](https://github.com/Tencent/tdesign-mobile-vue/assets/51228740/269e0eae-fdd2-49ec-a3b2-8251bb5d5d7a)
会有表头文字抖动和文字溢出的情况
在官网也能复现
修改css 表格高度为200px
![image](https://github.com/Tencent/tdesign-mobile-vue/assets/51228740/0ea6b206-01bf-43da-83bc-58a15b329130)
![image](https://github.com/Tencent/tdesign-mobile-vue/assets/51228740/a61daf5f-60d8-4847-9eda-d741a5c0d49b)
当你设置100%时 问题不复现
![image](https://github.com/Tencent/tdesign-mobile-vue/assets/51228740/3d19b423-e045-4000-b7bf-d6d7217854df)

### 框架版本

vue3.4

### 浏览器版本

最新谷歌

### 系统版本

win11

### Node版本

node20

**Comment by anlyyao** [comment]
@codeflyA 感谢反馈，h5端可能要直接看这个地址更准确 https://tdesign.tencent.com/mobile-vue/mobile.html#/table

**Comment by codeflyA** [comment]
![image](https://github.com/Tencent/tdesign-mobile-vue/assets/51228740/fc1b202f-fec8-4e68-9746-f41df1874631)
![image](https://github.com/Tencent/tdesign-mobile-vue/assets/51228740/7583d0a8-a1d1-402b-b77f-3a05439510cc)

**Comment by codeflyA** [comment]
![image](https://github.com/Tencent/tdesign-mobile-vue/assets/51228740/ff0aafa4-cd72-4a47-8187-9b15fe740c9f)

**Comment by codeflyA** [comment]
滚动时标题抖动 指快速上下滚动时，标题有轻微抖动，缩放状态下容易复现
