### ISSUE TITLE
官网中移动端展示效果有点别扭

### ISSUE THREAD

**Issue by Yomance** [Tencent/tdesign-mobile-vue#148]
这个能不能改成固定定位的呀，这个感觉有点别扭，有时候得翻到底下才能显示全，
![image](https://user-images.githubusercontent.com/57690311/173044196-47dbd6f9-08bc-4b98-8c69-a471757f3e6e.png)
有时候在底下看不到上面  在上面看不到底下的 
![image](https://user-images.githubusercontent.com/57690311/173044688-90ccf9ee-5b94-4a4f-a78d-4e58f98112e3.png)

**Comment by LeeJim** [comment]
你好，我明白你的问题，但不是很懂你的建议

**Comment by MrMPeter** [comment]
> 你好，我明白你的问题，但不是很懂你的建议

让右侧模拟机永远固定不动（fixed），不受文档流上下滚动的影响
