### ISSUE TITLE
构建发布文件问题

### ISSUE THREAD

**Issue by BuptStEve** [Tencent/tdesign-mobile-vue#1508]
### tdesign-mobile-vue 版本

 1.3.2

### 重现步骤

<img width="1463" alt="企业微信截图_b69258f2-33d8-47e7-9dbf-f1866a62ea35" src="https://github.com/user-attachments/assets/494de24b-71c7-44c2-8abe-01e67e7e69f9">

原因是发布的时候没有带上 `cjs/` 文件夹
<img width="373" alt="企业微信截图_d46b9ef5-d00f-447a-b769-5716230c1281" src="https://github.com/user-attachments/assets/97f6d90b-f797-47d9-91fd-8c1ffcc1b4f2">

**Comment by anlyyao** [comment]
@BuptStEve 处理了，周一发版带上
