### ISSUE TITLE
[Picker] 接口获取columns后  点击确定报错TypeError: Cannot read properties of undefined (reading 'label')

### ISSUE THREAD

**Issue by jetHall** [Tencent/tdesign-mobile-vue#1512]
### tdesign-mobile-vue 版本

1.3.2

### 重现步骤

 <t-popup v-model="examineStation.show" placement="bottom">
      <t-picker
          v-model="examineStation.examineStationId"
          :columns="approvalUnitList"
          @confirm="onExamineStationConfirm"
          @cancel="examineStation.show = false"
      />
  </t-popup>

------------------------------------------------
const examineStation = reactive({
  show: false,
  examineStationId: ref([]),
});
let approvalUnitList:any = ref([])
const listApprovalUnit = async (regionId:any) => {
    const res = await http.get('organization/listApprovalUnit',{regionId})
    res?.map((item: any) => {
        item.value = item.id
        item.label = item.organizationName
        return item
    })
    approvalUnitList.value.push(res)
}

报错信息：
TypeError: Cannot read properties of undefined (reading 'label')
    at tdesign-mobile-vue.js?v=923cba1e:17131:21
at Array.map (<anonymous>)
    at handleConfirm2 (tdesign-mobile-vue.js?v=923cba1e:17130:26)
    at callWithErrorHandling (chunk-U6BEPC57.js?v=923cba1e:1659:19)
    at callWithAsyncErrorHandling (chunk-U6BEPC57.js?v=923cba1e:1666:17)
    at HTMLDivElement.invoker (chunk-U6BEPC57.js?v=923cba1e:10297:5)

### 期望结果

点击确定不报错

**Comment by zhanglaoban2633** [comment]
**仔细看文档，你需要给columns套一层数组才能使用、我也提了这个问题、单选picker为什么要两层数组、其他picker都是正常的**
