### ISSUE TITLE
[Loading] 设置尺寸后出现旋转错位

### ISSUE THREAD

**Issue by Jasonyou-boy** [Tencent/tdesign-mobile-vue#1524]
### tdesign-mobile-vue 版本

1.3.3

### 重现步骤

Loading修改尺寸后出现旋转错位

**Comment by anlyyao** [comment]
<img width="1861" alt="企业微信截图_d1285333-a757-4ef1-b7a0-dea2a5d3a028" src="https://github.com/user-attachments/assets/578d9b54-7fa8-46ee-bd59-c15865470261">

辛苦确认是否为在chrome调试时出现旋转错位，如果是，该现象为已知问题。

结论是：调试时忽略它在chrome上表现，如果贸然移除真机可能就会出现bug

see https://github.com/Tencent/tdesign-vue-next/issues/358
