### ISSUE TITLE
[list] 增加从上方加载

### ISSUE THREAD

**Issue by k186** [Tencent/tdesign-mobile-vue#1526]
### 这个功能解决了什么问题

 可以用户自定义滚动方向来加载，目前发现其他框架有类似功能，但是实际体验很差,滚动条位置不对等诸多问题，重复触发；目前兼容方案采用下拉刷型的方式通过改变文案来提示加载历史信息；

### 你建议的方案是什么

希望list组件提供加载方向判断，满足易用性；非常感谢

**Comment by zhf521** [comment]
真的很需要这个功能，目前还没有特别好的组件满足同时可以下拉加载和上滑加载更多的功能

**Comment by anlyyao** [comment]
@k186 @HappierPuppy 感谢反馈～， list 组件本身不带刷新/加载功能，常结合 PullDownRefresh 实现下拉刷新，上滑加载可以通过 scroll 事件判断是否触底，可参考官网 **下拉刷新示例** https://tdesign.tencent.com/mobile-vue/components/list?tab=demo

**Comment by k186** [comment]
场景是 用于消息列表，用scroll能做，恶心的地方就是触发的阈值，市面vant 用的 就是scroll 实际效果很差，目前用下拉刷新 暂时处理的
