### ISSUE TITLE
[Loading] 按需加载在原生webview嵌入下无法转动动画失效

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-mobile-vue#1532]
### tdesign-mobile-vue 版本

1.3.4

### 重现链接

https://stackblitz.com/run?file=package.json

### 重现步骤

![image](https://github.com/user-attachments/assets/1f3f64c6-cb76-4e93-b98b-03c9147ee06f)
loading 无法转动
![image](https://github.com/user-attachments/assets/5cee18de-b4f2-4c97-81c5-222624147f27)
全局引入就没问题
为什么会这个情况

theme circular 会动画失效

https://github.com/user-attachments/assets/fae3fbf4-2174-4f93-bdf9-8e58e0a3666f

### 期望结果

转动

### 实际结果

没转动

**Comment by anlyyao** [comment]
fixed by https://github.com/Tencent/tdesign-common/pull/1907
