### ISSUE TITLE
[Swiper] vue3 响应式修改current属性不生效

### ISSUE THREAD

**Issue by panfuzeng** [Tencent/tdesign-mobile-vue#1549]
### tdesign-mobile-vue 版本
最新版本

### 重现步骤

动态修改current 没效果

## IssueShoot
- 预估时长: 3
- 期望完成时间: 2024-11-26 00:00:00 +0000 UTC
- 开发难度: 中
- 参与人数: 1
- 需求对接人: anlyyao
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by anlyyao** [comment]
@panfuzeng 官网不能直接复现的问题，辛苦贴一下使用代码

**Comment by qiujunhao92** [comment]
> @panfuzeng 官网不能直接复现的问题，辛苦贴一下使用代码

![screenshot-20241115-145527](https://github.com/user-attachments/assets/8c8eaf36-636c-47d1-a334-5a2355a0cf37)
这还需要贴代码呢,官网点这里直接没反应啊

**Comment by novlan1** [comment]
1. 内部缓存一个变量，用来区分组件主动变化还是外部导致的变化

**Comment by xifanTT** [comment]
https://github.com/Tencent/tdesign-mobile-vue/pull/1662/files
