### ISSUE TITLE
[tdesign-mobile-vue] 升级到1.4.0之后vite项目TDesignResolver失败

### ISSUE THREAD

**Issue by bostin** [Tencent/tdesign-mobile-vue#1558]
### tdesign-mobile-vue 版本

1.4.0

### 重现步骤

![QQ_1725081457745](https://github.com/user-attachments/assets/2975dcf8-eb29-42c3-9005-0c3435ccca65)

### 框架版本

"vue": "^3.4.37"
"unplugin-auto-import": "^0.18.2"
"unplugin-vue-components": "^0.27.4"
"vite": "^5.4.0"

### Node版本

v20.12.2

### 附加信息
"tdesign-mobile-vue": "1.3.4" 正常

**Comment by liweijie0812** [comment]
升级1.4.1，已修复此问题
