### ISSUE TITLE
[tdesign-mobile-vue] 通过npm安装，引入失败

### ISSUE THREAD

**Issue by wangzhuo1982** [Tencent/tdesign-mobile-vue#1559]
### tdesign-mobile-vue 版本

1.4.0

### 重现步骤

import TDesign from 'tdesign-vue-next';
提示错误
Failed to resolve entry for package "tdesign-mobile-vue". The package may have incorrect main/module/exports specified in its package.json.

### 框架版本

3.4.29

**Comment by wangzhuo1982** [comment]
webstorm中系统自带的VUE模板，按照官方示例在main.js中使用：

```
import './assets/main.css'
import 'tdesign-mobile-vue/es/style/index.css';

import { createApp } from 'vue'

import App from './App.vue'
import TDesign from 'tdesign-mobile-vue';
createApp(App).mount('#app')
const app = createApp(App);
app.use(TDesign);
```

在编译的时候提示错误：

`[vite] Internal server error: Failed to resolve entry for package "tdesign-mobile-vue". The package may have incorrect main/module/exports specified in its package.json.`

同样的情况使用桌面端

`import TDesign from 'tdesign-vue-next';`

正常

**Comment by liweijie0812** [comment]
升级1.4.1，已修复此问题
