### ISSUE TITLE
[组件名称] 希望能够自定义全局主题色

### ISSUE THREAD

**Issue by dd1994** [Tencent/tdesign-mobile-vue#1569]
### 这个功能解决了什么问题

目前小程序是能够自定义全局主题色，希望 Vue 版本也支持，因为一部分小程序一部分 webview 开发，希望主题能保持一致。

### 你建议的方案是什么

能够自定义全局主题色

**Comment by mkdirnow** [comment]
https://tdesign.tencent.com/vue-next/custom-theme
这个也适用移动端
