### ISSUE TITLE
[docs]  文档国际化错误

### ISSUE THREAD

**Issue by RSS1102** [Tencent/tdesign-mobile-vue#1584]
### tdesign-mobile-vue 版本

1.4.0

### 重现链接

https://tdesign.tencent.com/mobile-vue/components/input-en

### 重现步骤

在 mobile-vue 的英文情况下 input 组件页面发生错误

**Comment by anlyyao** [comment]
@RSS1102 收到反馈，我们处理一下

**Comment by liweijie0812** [comment]
> @RSS1102 收到反馈，我们处理一下
我改下
