### ISSUE TITLE
[Input 输入框] type="number"时，如何控制小数精度，对Input原始属性step不支持

### ISSUE THREAD

**Issue by lnbiuc** [Tencent/tdesign-mobile-vue#1594]
### tdesign-mobile-vue 版本

1.4.2

### 重现链接

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/step

### 框架版本

3.5.3

### Node版本

20

### 补充说明

<t-input v-model="entry.yem_price" align="right" type="number" step="0.01" label="单价" />
是否可以通过这种方式实现控制小数位为两位呢

感谢各位大佬对开源的贡献，感谢各位大佬帮助

**Comment by anlyyao** [comment]
@lnbiuc 方便提供下具体使用场景吗～。 原生 step 属性貌似也不能直接控制精度

**Comment by lnbiuc** [comment]
> @lnbiuc 方便提供下具体使用场景吗～。 原生 step 属性貌似也不能直接控制精度

感谢大佬回复！

输入金额的时候，需要控制只显示两位或四位小数

我注意到input有提供一个format props，也可以实现控制小数位数，但是我尝试了输入值的时候没有调用传入的func，是因为还在开发中吗

**Comment by anlyyao** [comment]
> > @lnbiuc 方便提供下具体使用场景吗～。 原生 step 属性貌似也不能直接控制精度
> 
> 感谢大佬回复！
> 
> 输入金额的时候，需要控制只显示两位或四位小数
> 
> 我注意到input有提供一个format props，也可以实现控制小数位数，但是我尝试了输入值的时候没有调用传入的func，是因为还在开发中吗

这个API确实还没实现，我补齐一下，预计本周发版可带
