### ISSUE TITLE
[Divider 分割符] windows系统，firefox系浏览器不显示分割符

### ISSUE THREAD

**Issue by lnbiuc** [Tencent/tdesign-mobile-vue#1601]
### tdesign-mobile-vue 版本

1.4.2

### 重现链接

https://tdesign.tencent.com/mobile-vue/components/divider

### 重现步骤

使用任意firefox浏览器，打开官网文档，右侧看不见分割线
![image](https://github.com/user-attachments/assets/ae07a1e8-857a-4958-8769-fc43f3196a74)
![image](https://github.com/user-attachments/assets/d99523af-9873-4048-bfc4-991aaf984cf2)

使用chrome正常显示
![image](https://github.com/user-attachments/assets/441ae8dd-6167-4b62-85b6-544f0e9c414b)

### 期望结果

支持firefox浏览器

### 框架版本

vue@3.5.3

### 浏览器版本

firefox

### 系统版本

windows11

### Node版本

22

### 补充说明

详细firefox版本信息
![image](https://github.com/user-attachments/assets/e65ef11c-0b3d-4426-8910-955c51f7b25e)

**Comment by anlyyao** [comment]
@lnbiuc 收到反馈，我来跟进处理哈～

**Comment by anlyyao** [comment]
看上去是win系统下火狐浏览器对 scale(.5) 的处理有问题，应该算浏览器的渲染bug吧，没有找到合适的解决方案，且 mobile vue/react 端以兼容移动端浏览器为主

你可以试试在外部覆盖组件伪类上的 transform: scaleY(0.5)，副作用是细线将无法处理成 0.5px
