### ISSUE TITLE
[ImageViewer 图片预览] 大尺寸图片（8192x5464），预览时无法左右拖动，无法缩小

### ISSUE THREAD

**Issue by lnbiuc** [Tencent/tdesign-mobile-vue#1607]
### tdesign-mobile-vue 版本

1.4.3

### 重现链接

https://github.com/lnbiuc/tdesign-mobile-vue-issue

### 重现步骤

点击按钮，打开图片预览

### 期望结果

初始大小应该可以看到完整图片，可以左右拖动图片，可以放大或缩小图片

### 实际结果

初始图片尺寸不正确，图片能缩小，图片不能左右拖动

### 框架版本

3.4.37

### 浏览器版本

任意

### 系统版本

任意

### Node版本

20

### 补充说明

![PixPin_2024-09-29_14-44-29](https://github.com/user-attachments/assets/e6b4c12e-3c7f-40b9-8c71-d53ca9ad3c38)

麻烦大佬回复下，目前没找到原因，已使用其他的图片预览组件暂替

**Comment by anlyyao** [comment]
@lnbiuc 暂时先单独引入一下 reset 样式， ` import 'tdesign-mobile-vue/dist/reset.css'`
