### ISSUE TITLE
[Popup] Popup 与 Toast 的 preventScrollThrough同时使用会导致禁止滑动

### ISSUE THREAD

**Issue by ry0513** [Tencent/tdesign-mobile-vue#1614]
### tdesign-mobile-vue 版本

1.4.3

### 重现链接

https://stackblitz.com/edit/nh8frt?file=src%2Fapp.vue

### 重现步骤

打开复现链接后，滑动屏幕，此时可以滑动；点击左上角打开Popup 后，点击获取数据，此时会关闭Popup，同时模拟加载数据，加载后再次滑动屏幕，此时无法滑动

### 期望结果

希望正常使用

### 实际结果

![image](https://github.com/user-attachments/assets/22d528e5-26f6-43bc-a288-39fe2f26c01f)
当加载后，body节点的class样式并没有消失导致无法滑动

### 框架版本

3.5.11

### 补充说明

需要打开 Popup 用来刷新数据
## IssueShoot
- 预估时长: 3
- 期望完成时间: 2024-10-18 00:00:00 +0000 UTC
- 开发难度: 中
- 参与人数: 1
- 需求对接人: anlyyao
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by anlyyao** [comment]
@ry0513 我这边在chrome浏览器打开链接， popup 关闭后，，body节点的class样式能按预期移除，内容可滑动，下面是录屏

https://github.com/user-attachments/assets/93d5a2a7-f9ae-44a1-b197-d04bcb9c37e1

**Comment by hkaikai** [comment]
已认领
