### ISSUE TITLE
[t-tab] 选项卡控件样式问题

### ISSUE THREAD

**Issue by omiAu** [Tencent/tdesign-mobile-vue#1626]
### tdesign-mobile-vue 版本

能

### 重现链接

https://stackblitz.com/edit/7t1qtv?file=src%2Fdemo.vue

### 重现步骤

![微信截图_20241024204247](https://github.com/user-attachments/assets/afb66932-9925-4960-a4d2-2bca37c5d362)
如图所示，移动端tab标签名字较长显示不完整，滑动效果不行

**Comment by anlyyao** [comment]
spaceEvenly 属性取 false，不然会优先均分

**Comment by anlyyao** [comment]
还要注意一下，swipeable 和 spaceEvenly 接收 boolean 类型
