### ISSUE TITLE
[button] loading 在 chrome 模拟的 iphone 设备中样式显示问题

### ISSUE THREAD

**Issue by puzzle9** [Tencent/tdesign-mobile-vue#1642]
### tdesign-mobile-vue 版本

1.5.0

### 重现步骤

- https://tdesign.tencent.com/mobile-vue/mobile.html#/button

![image](https://github.com/user-attachments/assets/95ccb6bb-0667-4e9b-bdcc-d75c267b5def)

### 浏览器版本

版本 133.0.6835.3（正式版本）dev （64 位）

### 系统版本

win11

### 补充说明

我不确定真机是怎么显示的

**Comment by anlyyao** [comment]
@puzzle9 

如果是chrome调试时出现旋转错位，该现象为已知问题。

结论是：调试时忽略它在chrome上表现，如果贸然移除真机可能就会出现bug

see https://github.com/Tencent/tdesign-vue-next/issues/358
