### ISSUE TITLE
[List] layout、size、split、stripe等属性未实现，与文档描述不一致

### ISSUE THREAD

**Issue by anlyyao** [Tencent/tdesign-mobile-vue#170]
### tdesign-mobile-vue 版本

0.8.6

### 期望结果

实现`props`：`layout`、`size`、`split`、`stripe`，与文档保持一致

### 实际结果

`layout`、`size`、`split`、`stripe`均未实现，与文档描述不符

**Comment by LeeJim** [comment]
已移除对应未实现的 API
