### ISSUE TITLE
[Message] API文档已更新，需补充所缺属性：marquee

### ISSUE THREAD

**Issue by anlyyao** [Tencent/tdesign-mobile-vue#174]
### tdesign-mobile-vue 版本

0.8.6

### 重现链接

https://github.com/Tencent/tdesign-mobile-vue/tree/feat/message/props

### 重现步骤

[API差异](https://github.com/Tencent/tdesign-mobile-vue/commit/192e839e6d7818b4c45a0092e0eb75bd0d616ed4)

### 期望结果

实现`props`：
- `marquee`

### 实际结果

文档中缺`marquee`描述，`marquee`功能也未实现

### 补充说明

1.  API：`feat/message/props`分支下，`Message`组件的`message.md`、`props.ts`、`type.ts`为最新`API`文档及功能需求，需对齐该文档，补充`marquee`属性。
2.  开发：参照API文档，基于[feat/message/props分支](https://github.com/Tencent/tdesign-mobile-vue/tree/feat/message/props)

**Comment by douxpang** [comment]
认领，8.9前提交

**Comment by anlyyao** [comment]
后续我来跟进～
