### ISSUE TITLE
进展总览

### ISSUE THREAD

**Issue by anlyyao** [Tencent/tdesign-mobile-vue#178]
> 大家认领组件的话，可以在本 issue 评论

后续将会在这个 issue 里持续更新 Mobile Vue 的工作安排和进展

## API实现
- [x] 基础组件
  - [x] Button 
  - [x] Divider
  - [x] Icon

- [x] 导航
  - [x] DropdownMenu
  - [x] Indexes
  - [x] Steps
  - [x] Tabbar
  - [x] Tabs

- [ ] 输入
  - [x] Checkbox 【 @anlyyao  】 #195 
  - #150 
  - #151 
  - #152 
  - [x] DateTimePicker  【 @Dengzygx 】
  - #153 
  - [x] Fab 【 @anlyyao 】  #182 
  - #154 
  - #155 
  - [x] Input  【 @anlyyao 】  #181 
  - #156 
  - #157 
  - [x] Picker 【 @Dengzygx 】#209
  - #159 
  - #158 
  - [x] Radio 【 @anlyyao 】 #192 
  - #188 
  - [x] Rate 【 @anlyyao 】 #185 
  - #160 
  - [x] Search 【@LeeJim 】#201
  - #161 
  - [x] Slider
  - [x] Stepper
  - [x] Switch
  - [x] Textarea
  - [x] Upload  【 @wwlh200 】#205
  - #162
  - #163
  - #164 
  - #165

- [ ] 数据展示
  - [x] Avatar
  - [x] Badge 【 @robinWongM 】 #142 
  - #127 
  - [x] Cell 【 @anlyyao 】  #184 
  - #168 
  - [x] Collapse
  - [x] CountDown
  - [x] Drawer 【 @ruige24601 】 #186 
  - #130 
  - #167 
  - [x] Grid
  - [x] Image
  - [ ] ImageViewer
  - #169 
  - [x] List 【 @[ZTao-z](https://github.com/ZTao-z)】#200
  - [x] Loading 【 @LeeJim  】 #191 
  - #172 
  - [x] NoticeBar
  - [x] Skeleton
  - [x] Sticky
  - [x] SwiperCell
  - [x] Swiper 【 @anlyyao 】 #197 
  - #171 
  - [x] Tag

- [ ] 消息提醒
  - [x] ActionSheet
  - [x] Backtop
  - [x] Dialog 【 @LeeJim 】 #193 
  - #173 
  - [ ] Message 【 @anlyyao 】 #196 
  - #174 
  - [x] Popup
  - [x] PullDownRefresh
  - [x] Toast 【 @oceanlvr 】#204
  - #176 

## 文档改进
- [ ] 基础组件
- [x] 导航
  - [x] DropdownMenu 【 @anlyyao  】 #180 
  - #177 
- [ ] 输入
- [x] 数据展示
  - [x] Progress 【 @anlyyao 】  #179 
  - #175 
- [ ] 消息提醒

## 视觉问题修复
- [ ] 基础组件

**Comment by anlyyao** [comment]
Progress 我来处理。
issue：https://github.com/Tencent/tdesign-mobile-vue/issues/175

鉴于[小程序端](https://tdesign.tencent.com/miniprogram/components/progress?tab=api)目前也未实现 `size` 、`theme` 属性，将文档中`size` 、`theme` 相关内容移进行移除。

**Comment by anlyyao** [comment]
DropdownMenu 我来跟进～～
issue：https://github.com/Tencent/tdesign-mobile-vue/issues/177

**Comment by anlyyao** [comment]
认领 input
issue：
- https://github.com/Tencent/tdesign-mobile-vue/issues/157
- https://github.com/Tencent/tdesign-mobile-vue/issues/156

**Comment by anlyyao** [comment]
认领fab
issue： 
- https://github.com/Tencent/tdesign-mobile-vue/issues/154
- https://github.com/Tencent/tdesign-mobile-vue/issues/155

**Comment by anlyyao** [comment]
认领 cell
issue：
- https://github.com/Tencent/tdesign-mobile-vue/issues/168

**Comment by anlyyao** [comment]
认领drawer
issue：
- https://github.com/Tencent/tdesign-mobile-vue/issues/167

**Comment by anlyyao** [comment]
认领Rate
issue：
- #160

**Comment by Dengzygx** [comment]
认领 Picker DateTimePicker
#159 
#153 
#158

**Comment by anlyyao** [comment]
认领Radio
- #188

**Comment by Dengzygx** [comment]
认领 Picker
#159 
#158

**Comment by anlyyao** [comment]
认领Button
- #183

**Comment by ZTao-z** [comment]
认领 List
#170

**Comment by ruige24601** [comment]
认领Drawer
issue:
https://github.com/Tencent/tdesign-mobile-vue/pull/186
https://github.com/Tencent/tdesign-mobile-vue/issues/130
https://github.com/Tencent/tdesign-mobile-vue/issues/167
