### ISSUE TITLE
[dropdownMenu] 示例代码有误

### ISSUE THREAD

**Issue by w453145157** [Tencent/tdesign-mobile-vue#207]
### tdesign-mobile-vue 版本

0.8.6

### 重现链接

https://stackblitz.com/run?file=src%2Fdemo.vue

### 重现步骤

树形下拉的demo，示例有误（有未使用组件，校验报错）
![image](https://user-images.githubusercontent.com/18654990/176339740-0745f02d-dc91-44bf-b50e-367c7dfa2d19.png)

**Comment by LeeJim** [comment]
我处理下
