### ISSUE TITLE
[Picker 选择器] 选择日期时出现的问题

### ISSUE THREAD

**Issue by ytzfwyz521** [Tencent/tdesign-mobile-vue#222]
### tdesign-mobile-vue 版本

0.9.0

### 重现链接

https://tdesign.tencent.com/mobile-vue/components/picker?tab=demo

### 重现步骤

官方示例代码如下： 
 <t-popup v-model="dateState.show" placement="bottom">
    <t-picker v-model="dateState.date" :columns="dateColumns" @confirm="onConfirm" @cancel="onCancel" @pick="onPick" />
  </t-popup>

### 期望结果

选择日期的各列如果不经过滑动，就不会有值，换句话说，就是不经过滑动的列，没有赋予它点击确定后的默认值。
场景一操作步骤：选择日期后，若只滑动第一列-年，滑到2010，后面两列都不滑动，都为默认即1月1号。点击确定按钮后，获取到的值应该是[2010,1,1]。
场景二操作步骤：选择日期后，若只滑动第一列-年 和第三列-日，第二列不滑动，将第一列滑到2010，第三列滑动到2号，第二列都不滑动，为默认1月。点击确定按钮后，获取到的值应该是[2010,1,2]。

### 实际结果

场景一操作步骤：选择日期后，若只滑动第一列-年，滑到2010，后面两列都不滑动，都为默认即1月1号。点击确定按钮后，只获取到年的数值[2010]
场景二操作步骤：选择日期后，若只滑动第一列-年 和第三列-日，第二列不滑动，将第一列滑到2010，第三列滑动到2号，第二列都不滑动，为默认1月。点击确定按钮后，只获取到年和日的数值，显示为[2010,null,2]

**Comment by LeeJim** [comment]
@Dengzygx 有时间记得看看

**Comment by douxpang** [comment]
认领
