### ISSUE TITLE
📌 计划 & 进展

### ISSUE THREAD

**Issue by LeeJim** [Tencent/tdesign-mobile-vue#224]
> ❗️❗️认领规则：在 **关联 Issue** 下评论 “我来跟进” 即可认领 issue，我会定期汇总在这里
### 新组件
组件名 | 状态 | 负责人 | 关联 Issue | 关联 discussion | 关联PR
--|--|--|--|--| --
Cascader 级联选择器 | 🔵 已完成  | @oceanlvr, @LeeJim   | #234 | https://github.com/Tencent/tdesign/discussions/157 | -
Calendar 日历| 🔵 已完成 | @LadyChatterleyLover, @LeeJim  | #260  |  https://github.com/Tencent/tdesign/discussions/143 | #325 
Result 结果 | 🔵 已完成 | @anlyyao   | - | -| #243 

### 新特性
组件名 | 状态 | 负责人 | 关联 Issue | 关联PR
--|--|--|--|--
Tag 标签 | 🔵 已完成  | @anlyyao  | - | #229 
Input 输入框| 🟡 未认领  | -  | - | -
Swiper 轮播图| 🔵 已完成  | @anlyyao  | - | #262 
Skeleton 骨架屏 | 🔵 已完成  | @anlyyao  | - | #239
Popup 弹出层| 🟢 进行中 | @LeeJim | - | -

## 🚥 测试覆盖

具体进展，可查看 #271 （已于 2022.11.4 完成）

## ✍🏼 示例代码改造

具体进展，可查看 #413

## 🎨  主题配置

0）设计师整理 CSS Token
1）抽取 CSS Variable
2）个组件使用 CSS Variable

## 其他

- [ ] SFC 改造升级 JSX

**Comment by oceanlvr** [comment]
认领 Cascader 级联选择器

**Comment by anlyyao** [comment]
认领 tag

**Comment by LadyChatterleyLover** [comment]
认领Calendar 日历

**Comment by anlyyao** [comment]
认领swiper
