### ISSUE TITLE
[Message] Message not work

### ISSUE THREAD

**Issue by justforuse** [Tencent/tdesign-mobile-vue#228]
### tdesign-mobile-vue 版本

0.9.0

### 重现链接

https://tdesign.tencent.com/mobile-vue/components/message

### 补充说明

文档示例貌似不work

**Comment by justforuse** [comment]
刚看了下，可以用了👍

![image](https://user-images.githubusercontent.com/11868477/178911146-3d9c036c-4726-4a27-b33c-defdd023d4d5.png)

**Comment by LeeJim** [comment]
OK 那先关闭了
