### ISSUE TITLE
关于桌面和移动端混合开发的需求

### ISSUE THREAD

**Issue by Yuii-guoguo** [Tencent/tdesign-mobile-vue#244]
### 这个功能解决了什么问题

tdesign-vue-next和tdesign-mobile-vue同时引入会报错

### 你建议的方案是什么

希望出一个相关操作步骤,推出混合开发的方案

**Comment by Yuii-guoguo** [comment]
引用mobile的组件会报无法引入，看了下报错信息是引入错误的路径了,路径是桌面端的。

**Comment by Yuii-guoguo** [comment]
`import TDesign from 'tdesign-vue-next';
import TDesignM from 'tdesign-mobile-vue';
const app = createApp(App);
app.use(TDesign);
app.use(TDesignM);
app.mount('#app');`

这样引入就会报错.

**Comment by Yuii-guoguo** [comment]
环境是vue3+vite

**Comment by mhy-priv** [comment]
@Yuii-guoguo 请问有解决吗

**Comment by Yuii-guoguo** [comment]
> @Yuii-guoguo 请问有解决吗

已经解决了，谢谢.
