### ISSUE TITLE
[单元格] click为什么反馈MouseEvent？

### ISSUE THREAD

**Issue by Yuii-guoguo** [Tencent/tdesign-mobile-vue#245]
### tdesign-mobile-vue 版本

0.9.2

### 重现步骤

点击单元格组件

### 期望结果

返回点击单元格属性

### 实际结果

返回MouseEvent

### 框架版本

Vue3

### 补充说明

我没想到click反馈MouseEvent的意义在哪？啥标志性属性都没有。

**Comment by LeeJim** [comment]
grid 没有定义任何事件，你说的 MouseEvent 就原生事件。
麻烦说下你明确的需求吧
