### ISSUE TITLE
[t-dialog] confirmBtn的插槽不生效

### ISSUE THREAD

**Issue by Jack-yo** [Tencent/tdesign-mobile-vue#246]
### tdesign-mobile-vue 版本

0.9.2

### 重现链接

https://github.com/Tencent/tdesign-mobile-vue/blob/0.9.2/src/popup/popup.vue

### 重现步骤

t-dialog组件引用的时候，涉及到popup组件，popup组件中使用到overlay，没有传入visible这个必须属性。导致t-dialog的确定按钮插槽无法使用。

### 期望结果

t-dialog可以传入插槽

### 实际结果

t-dialog传入插槽不成功

**Comment by LeeJim** [comment]
我来处理下

**Comment by LeeJim** [comment]
看了下 confirmBtn 插槽可以正常使用

**Comment by Jack-yo** [comment]
你的测试demo是？

**Comment by LeeJim** [comment]
麻烦用 codesandbox 提供下你的问题代码？

**Comment by Jack-yo** [comment]
https://codesandbox.io/s/wonderful-wozniak-1ertu2?file=/src/components/HelloWorld.vue 这是demo链接。我看了你们的源代码，怀疑是插槽实现的时候，不应该是先判断是否有值再去slot，而是在slot里面判断是否有内联属性才显示默认插槽，否则就需要插入用户的插槽

**Comment by Jack-yo** [comment]
你可以在我的demo的helloworld组件中的t-dialog内联content="--"属性，然后我写的插槽内容就会展示出来，这个情况正正验证我说的那个问题。

**Comment by LeeJim** [comment]
好的。我看看

**Comment by LeeJim** [comment]
确实有问题，我来处理下
