### ISSUE TITLE
[官网] 官网路由路径匹配不生效

### ISSUE THREAD

**Issue by VeryHandSomeBoy** [Tencent/tdesign-mobile-vue#252]
### tdesign-mobile-vue 版本

0.9.2

### 重现链接

https://tdesign.tencent.com/mobile-vue/overview

### 重现步骤

访问[官网](https://tdesign.tencent.com/mobile-vue/overview)的路径为`https://tdesign.tencent.com/mobile-vue/overview`无法正常访问，而访问[正确的官网](https://tdesign.tencent.com/mobile-vue)可以正常访问，发现`https://tdesign.tencent.com/mobile-vue`会自动跳转到`https://tdesign.tencent.com/mobile-vue/overview`,刷新时白屏

### 期望结果

直接访问`https://tdesign.tencent.com/mobile-vue/overview`能正常访问，或刷新可用

### 实际结果

刷新白屏，无法直接访问

### 补充说明

应该是路由匹配问题

**Comment by LeeJim** [comment]
我来看看

**Comment by anlyyao** [comment]
已修复
