### ISSUE TITLE
[List] 上拉加载时不触发scroll

### ISSUE THREAD

**Issue by VeryHandSomeBoy** [Tencent/tdesign-mobile-vue#267]
### tdesign-mobile-vue 版本

0.10.1

### 重现步骤

正常使用`t-list`组件，上拉加载时无法触发scroll事件，导致上拉加载失效

经过测试和探索，发现得为`.t-list`加上高度才可以触发事件

### 期望结果

上拉时触发scroll事件

### 实际结果

没有触发事件

### 框架版本

Vue(3.2.25)

### 浏览器版本

Chrome(103.0.5060.114)

### 系统版本

MACOS(12.4)

### Node版本

16.16.9

### 补充说明

经过测试和探索，发现为`.t-list`加上高度才可以触发事件

这应该是设计上的问题，在文档里并没有说明得为自带的`.t-list`的class设置高度属性，起码得为`height: 100%`继承父元素的高度，否则用户根本无从知晓得为其设置该属性

**Comment by VeryHandSomeBoy** [comment]
还有个问题，如果和`pull-down-refresh`组件配合使用，还得一层层指定DOM父元素的高度，得去改内置的样式

**Comment by Dengzygx** [comment]
收到，正在处理
