### ISSUE TITLE
[Noticebar] 增加多条广告内容纵向滚动展示

### ISSUE THREAD

**Issue by hsk1995** [Tencent/tdesign-mobile-vue#268]
### 这个功能解决了什么问题

当广告内容不只一条时
目前组件展示只能拼接长字符串用跑马灯展示
但是每条广告都需要点击事件，需要分别传参

### 你建议的方案是什么

[{"id":1,"title":"测试广告1","click":"a",},{"id":2,"title":"测试广告2","click":"b",}]
纵向滚动展示，content支持传array格式

**Comment by anlyyao** [comment]
已被认领。

认领人： @wanwenyun
时间节点： 8.22 前

**Comment by TingShine** [comment]
还可以继续领取不

**Comment by ZWkang** [comment]
@anlyyao 这个还需要开发么，我可以来做这个

**Comment by anlyyao** [comment]
@ZWkang   🤝需要的。但容我们先讨论一下API， 等API定出来，我call你～

**Comment by ZWkang** [comment]
@anlyyao 好的
