### ISSUE TITLE
[Dialog] 示例代码不生效

### ISSUE THREAD

**Issue by will-** [Tencent/tdesign-mobile-vue#279]
### tdesign-mobile-vue 版本

0.10.2

### 重现链接

https://stackblitz.com/edit/angular-r5yhkb?file=src/demo.vue

### 重现步骤

在`dialog`面板，点击运行示例代码

### 期望结果

弹出对话框

**Comment by anlyyao** [comment]
负责人@zyqq 
时间节点：8.22 前
