### ISSUE TITLE
[Loading] 加载组件的Icon在ios端显示异常

### ISSUE THREAD

**Issue by VeryHandSomeBoy** [Tencent/tdesign-mobile-vue#281]
### tdesign-mobile-vue 版本

0.10.1

### 重现步骤

在微信或企业微信ios端，使用该组件

### 期望结果

icon正常转动

### 实际结果

icon显示异常

### 框架版本

Vue(3.2.25)

### 浏览器版本

Chrome(103.0.5060.114)

### 系统版本

MACOS(12.4)

### Node版本

16.16.9

### 补充说明

需要改font-size为14px才显示正常，但对安卓来说字体太小了

**Comment by palmcivet** [comment]
我来尝试修复这个问题~

**Comment by VeryHandSomeBoy** [comment]
> 我来尝试修复这个问题~
昨晚看了一下，是ua的问题，在[源码](https://github.com/Tencent/tdesign-common/blob/a58d86175ed864e473a0a1111e0f2dbd1e9e4e62/js/loading/circle-adapter.ts)中ua在企微的判断不能满足，isSafari的值为false，这个要关注一下
