### ISSUE TITLE
[Search] 设置默认值不展示，需要点击才能显示

### ISSUE THREAD

**Issue by CherishDing** [Tencent/tdesign-mobile-vue#282]
### tdesign-mobile-vue 版本

0.10.2

### 重现步骤

1、设置defaultValue 不生效，初始化时给的初始值需要点击才能显示
2、focus event不生效, 默认设置是否聚集focus 不生效
3、给出的Demo示例不完整，clear,defaultValue等使用不明确，看源码demo设置是否聚焦用的是autofocus，但文档是写focus

### 期望结果

默认状态时，展示所赋的值，而不是需要点击才展示
设置focus 为true时，默认聚集状态

### 实际结果

不展示默认值，不聚集

### 框架版本

Vue(3.2.31)

### Node版本

Node(16.13.1)

**Comment by VeryHandSomeBoy** [comment]
我来看下

**Comment by VeryHandSomeBoy** [comment]
我看到代码中，focus是search组件的props，auto-focus是input组件的props，应该是没问题的，如果没有显示效果可能要给input组件提个issue
