### ISSUE TITLE
[Popup] visible 字段控制显示后无法关闭

### ISSUE THREAD

**Issue by zyqq** [Tencent/tdesign-mobile-vue#290]
### tdesign-mobile-vue 版本

0.10.3

### 重现链接

https://stackblitz.com/edit/angular-r5yhkb-hjxeet?file=README.md,src%2Fdemo.vue

### 重现步骤

将示例代码中v-model改为:visible

### 期望结果

显示后，点击遮罩层会关闭

### 实际结果

遮罩层无法关闭

### Node版本

v16.14.2

**Comment by Calvest** [comment]
@zyqq 使用 `:visible` 这种方式需要额外写一个监听函数 `@close="center = false"` 手动关闭 popup

**Comment by zyqq** [comment]
> 

那用v-model:visible又不用加监听函数，所以理解可以组件底层帮忙自动监听的。

**Comment by zyqq** [comment]
而且一直有个疑问，v-model:visible这种写法eslint也是不推荐的，为啥还要支持这种语法糖，觉得v-model就够了

**Comment by LeeJim** [comment]
确实可以的，我来优化下

**Comment by LeeJim** [comment]
使用 `:visible` 就是明确控制 visible 了，需要手动控制 visible。
如果此时我内部将这个 visible 设置成 false。你想再次打开 popup 就会失效，因为你传过来的 visible 一直是 true。
