### ISSUE TITLE
DateTimePicker 时间选择器 示例代码内 "t-popup"标签的属性名"position" 错误 

### ISSUE THREAD

**Issue by eya46** [Tencent/tdesign-mobile-vue#339]
网址:
https://tdesign.tencent.com/mobile-vue/components/date-time-picker

DateTimePicker 时间选择器 的 四个示例代码中，t-popup标签的position属性名错误
查看了下 t-popup (Popup 弹出层) 的API，里面不存在 position属性，可能是 placement 这个属性名

**Comment by Dengzygx** [comment]
已处理
