### ISSUE TITLE
[Grid] image Slot 无效

### ISSUE THREAD

**Issue by 81867370** [Tencent/tdesign-mobile-vue#351]
### tdesign-mobile-vue 版本

0.10.5

### 重现链接

https://stackblitz.com/edit/angular-somgtw-v6zk7w?file=src%2Fdemo.vue

### 重现步骤

无

### 期望结果

无

### 实际结果

无

### 补充说明

无

**Comment by anlyyao** [comment]
@Nice-PLQ  t-grid-item 设置 :image="true"～

**Comment by LeeJim** [comment]
我来处理下
