### ISSUE TITLE
[tabs] 选项卡会执行两次

### ISSUE THREAD

**Issue by maoyuxuan** [Tencent/tdesign-mobile-vue#353]
### tdesign-mobile-vue 版本

0.10.3

### 重现步骤

<t-tabs default-value="first" @on-change="onChange">
    <t-tab-panel value="first" label="标签页一"> 引入自定义组件，选项卡会执行两次 </t-tab-panel>
    <t-tab-panel value="second" label="标签页二">引入自定义组件，选项卡会执行两次 </t-tab-panel>
  </t-tabs>

### 期望结果

选项卡会执行一次

### 实际结果

引入自定义组件，选项卡会执行两次

**Comment by TingShine** [comment]
可以看看 https://github.com/Tencent/tdesign-mobile-vue/issues/253

**Comment by LeeJim** [comment]
和 #253 重复了，已在 0.10.1 中修复了此问题，麻烦升级到这个版本以上看看。
我这边就先关闭了
