### ISSUE TITLE
[upload] 上传后，控制台接口已经上传成功，但组件无任何反应，无预览图，控制台有报错

### ISSUE THREAD

**Issue by MrMPeter** [Tencent/tdesign-mobile-vue#372]
### tdesign-mobile-vue 版本

0.10.6

### 重现链接

官方示例

### 实际结果

报错信息：index.c2f8e9fd.js:15 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'status')

**Comment by anlyyao** [comment]
@MrMPeter  更新到最新版试试～

**Comment by anlyyao** [comment]
@MrMPeter 请问还有问题吗？ 如果没有了 我这边就先关闭issue了哈～

**Comment by anlyyao** [comment]
> > @MrMPeter 请问还有问题吗？ 如果没有了 我这边就先关闭issue了哈～
> 
> 最新版已修复，关掉吧

好的。 感谢支持和反馈～
