### ISSUE TITLE
[Avatar] api增加fit对img的object-fit裁切控制

### ISSUE THREAD

**Issue by balabalanobala** [Tencent/tdesign-mobile-vue#378]
### 这个功能解决了什么问题

不同项目中，可能头像并没有在上传时就裁切成1比1的正方形，增加此功能代价不高，方便在后端头像图片非正方形时控制展示的样式

### 你建议的方案是什么

像TDesign的Image组件一样通过api fit来实现控制
![image](https://user-images.githubusercontent.com/67864956/192934970-e8b2bb52-6d51-45ae-a69d-163788662431.png)

**Comment by anlyyao** [comment]
认领～
