### ISSUE TITLE
[POPUP] 修改overlay的背景色

### ISSUE THREAD

**Issue by Orange1991** [Tencent/tdesign-mobile-vue#384]
### tdesign-mobile-vue 版本

0.11.0

### 重现步骤

```
<t-popup v-model="visible" placement="bottom" :customStyle="background-color: rgba(0,0,0,.3)">
  <div>anything</div>
</t-popup>
```

### 期望结果

期望修改 t-overlay 的背景色为 rgba(0,0,0,.3)

### 实际结果

实际，颜色被设置到了`t-popup`上，并未覆盖`t-overlay`的默认背景色
<img width="824" alt="image" src="https://user-images.githubusercontent.com/9190259/194550559-4c5f8193-e278-480c-9e06-4de1e764b7d2.png">

<img width="282" alt="image" src="https://user-images.githubusercontent.com/9190259/194550762-be3d6813-3ed6-4659-951e-893dc7ee4790.png">

### 框架版本

Vue(3.0.0)

**Comment by Orange1991** [comment]
Anybody in? @Nice-PLQ

**Comment by anlyyao** [comment]
在 Overlay 上新增了 customStyle属性，支持自定义遮罩样式。 popup 可以通过 overlayProps 去修改遮罩样式
<img width="643" alt="截屏2022-10-12 19 24 52" src="https://user-images.githubusercontent.com/51158141/195330891-060de9aa-330c-49b5-b97a-221514abeaff.png">
