### ISSUE TITLE
[icon] 安装后是使用命令不显示，报错不知道怎么解决

### ISSUE THREAD

**Issue by DaZhewei** [Tencent/tdesign-mobile-vue#389]
### tdesign 版本

移动端0.10.6

### 框架版本

vue3.2

### 系统版本

windows11

### 补充说明

![image](https://user-images.githubusercontent.com/111034689/192243158-11bb81d1-1b19-4583-b64d-a781fddb0e7f.png)

**Comment by anlyyao** [comment]
@DaZhewei  提供一下可复现代码吧～ 我这边icon使用正常的。 官网也有 icon 的使用示例，可以参考一下

**Comment by DaZhewei** [comment]
npm i tdesign-icons-vue-next  安装后没有再main.js里面引入  引入报多次引入的错误   因为引入注册这个了tdesign-mobile-vue
引入后写的这个 <icon name="check-circle-filled" /> 就不行了    页面内单独引入import { Icon } from 'tdesign-icons-vue-next';这个也不行

**Comment by anlyyao** [comment]
@DaZhewei  引入 tdesign-mobile-vue 之后，会携带 图标库，不用额外安装了呀～

**Comment by LeeJim** [comment]
> npm i tdesign-icons-vue-next 安装后没有再main.js里面引入 引入报多次引入的错误 因为引入注册这个了tdesign-mobile-vue 引入后写的这个 就不行了 页面内单独引入import { Icon } from 'tdesign-icons-vue-next';这个也不行

引入了 Icon 之后，需要在 Components 里注册才能用

**Comment by anlyyao** [comment]
@DaZhewei 请问还有问题吗？ 如果没有了 我这边就先关闭issue了哈～
