### ISSUE TITLE
✍🏼  mobile-vue 示例代码改造

### ISSUE THREAD

**Issue by anlyyao** [Tencent/tdesign-mobile-vue#413]
由于目前官网中组件DEMO和示例代码存在一些问题，因此开始对官网的示例代码进行改造升级。

⚠️ 感兴趣的朋友可以直接评论认领，认领后务必先翻阅 [mobile-vue: 示例改造指引](https://github.com/Tencent/tdesign-mobile-vue/wiki/mobile-vue%EF%BC%9A%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81%E6%94%B9%E9%80%A0%E6%8C%87%E5%BC%95)，里面有具体操作说明和流程

## 问题：
1. 示例代码存在使用错误
2. 示例代码和组件 DEMO 不一致
3. 组件DEMO未对齐视觉稿
## 要求：
1. 修复使用错误，示例代码的语法糖升级为 setup
2. 组件 DEMO 与示例代码保持一致
3. 对齐视觉稿

### 基础
- [x] Button @TingShine #475 
- [x] Fab @yuanmeda #435 

### 布局
- [x] Cell 
- [x] Divider @yuanmeda #436 
- [x] Grid 

### 导航
- [x] DropdownMenu @yuanmeda #440 
- [x] Indexes  @yuanmeda #437 
- [x] NavBar @TingShine  #391 
- [x] Steps @yuanmeda #459 
- [x] Sticky  @yuanmeda #438 
- [x] TabBar @yuanmeda #433 
- [x] Tabs 

### 输入

- [x] Calendar
- [x] Cascader @TingShine #444 
- [x] Checkbox  @yuanmeda #434 
- [x] DateTimePicker 
- [x] Input @palmcivet #431 
- [x] Picker  
- [x] Radio 
- [x] Rate @yuanmeda #439 
- [x] Search @palmcivet #445 
- [x] Slider @yuanmeda #458 
- [x] Stepper @TingShine #443 
- [x] Switch 
- [x] Textarea @palmcivet #432 
- [x] Upload @yuanmeda #460 

### 数据展示
- [x] Avatar @anlyyao  #417 
- [x] Badge @teal-front #420 
- [x] Collapse @yuanmeda #461 
- [x] CountDown @TingShine #477 
- [x] Image @TingShine #478 
- [x] ImageViewer @yuanmeda #463 
- [x] List @LeeJim #427 #466
- [x] Result 
- [x] Skeleton 
- [x] Swiper
- [x] Tag 

### 消息提醒
- [x] ActionSheet @yuanmeda #462 
- [x] Backtop @yuanmeda #468 
- [x] Dialog @LeeJim #422
- [x] Drawer
- [x] Loading @lockiechen #481 
- [x] Message @anlyyao #429
- [x] NoticeBar  @anlyyao #421 @byq1213 #465
- [x] Overlay 
- [x] Popup 
- [x] Progress @xxxlj #472 
- [x] PullDownRefresh @yuanmeda #470 
- [x] SwipeCell @wwlh200 #473 
- [x] Toast @yuanmeda #430  

### 11.12 - 11.14
- 完成 = 50， 完成度 = 100%

### 11.5 - 11.11
- 完成 = 48， CR= 2， 完成度 = 96%

### 10.29 - 11.4
- 完成 = 33， CR= 2， 完成度 = 66%
- 新增贡献者 1 名

### 10.22 - 10.28
⚠️ 涉及 common 改动，mobile-react 对应组件示例同步改造中
- 补充  [mobile-vue: 示例改造指引](https://github.com/Tencent/tdesign-mobile-vue/wiki/mobile-vue%EF%BC%9A%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81%E6%94%B9%E9%80%A0%E6%8C%87%E5%BC%95)文档
- 新增贡献者 2 名
- 完成 = 26, CR = 4,  完成度 52%

### 10.17 - 10.21
- 开启demo示例改造
- 完成 = 14, CR = 1,  完成度 28%

**Comment by yuanmeda** [comment]
认领 toast 示例代码改造

**Comment by teal-front** [comment]
认领 badge示例代码改造

**Comment by lockiechen** [comment]
认领 loading 示例代码改造

**Comment by palmcivet** [comment]
认领 Input 和 Textarea 的示例代码改造

**Comment by sommouns** [comment]
认领NoticeBar 示例代码改造

**Comment by anlyyao** [comment]
@sommouns  NoticeBar组件 已经搞完了，请重新认领一个哦～  第一条评论中有详细完成状态

**Comment by wwlh200** [comment]
认领SwipeCell 示例代码改造

**Comment by anlyyao** [comment]
@yuanmeda  list 已完成～ 注意一下哦

**Comment by xxxlj** [comment]
认领 progress 示例代码改造

**Comment by anlyyao** [comment]
🎉🎉  示例代码改造已全部完成，该条issue就关闭啦！
关于TD周边，后续会有人专门的同学联系发放，请各位贡献者们关注各自Github上的预留📮～
