### ISSUE TITLE
[Picker 选择器] 选中时.t-cell__right-icon宽度从24px变成32px；选中一次时，再次滑动picker选项还没点击确定时选中值就已经自动随之变化

### ISSUE THREAD

**Issue by balabalanobala** [Tencent/tdesign-mobile-vue#415]
### tdesign-mobile-vue 版本

0.11.0

### 重现链接

https://tdesign.tencent.com/mobile-vue/components/picker

### 重现步骤

1.选中时.t-cell__right-icon宽度从24px变成32px
![image](https://user-images.githubusercontent.com/67864956/196323735-e783fe0c-1a21-42de-8700-4eb432924931.png)
![image](https://user-images.githubusercontent.com/67864956/196323775-0770ceb0-6e65-4f9a-8b0a-daf506d25fa9.png)
![image](https://user-images.githubusercontent.com/67864956/196324955-d49c6231-a1f2-413c-b24f-c0104e595815.png)
2.选中一次时，再次滑动picker选项还没点击确定时选中值就已经自动随之变化
![image](https://user-images.githubusercontent.com/67864956/196324050-b1228614-2db2-45e7-a09f-db62fe4953eb.png)
![image](https://user-images.githubusercontent.com/67864956/196325058-e3379855-b67b-475c-92a9-b3c9adc74976.png)
![image](https://user-images.githubusercontent.com/67864956/196325178-8bc2a52a-ed8b-47f6-8d82-c9816b6721c0.png)

### 期望结果

1.选中时.t-cell__right-icon宽度从24px变成32px
   样式统一
![image](https://user-images.githubusercontent.com/67864956/196325270-84cfdad8-282d-4ce0-a3d5-de7cd233e5e6.png)
2.选中一次时，再次滑动picker选项还没点击确定时选中值就已经自动随之变化
   只有点击确定，选中值才会跟着改变

### 实际结果

1.选中时.t-cell__right-icon宽度从24px变成32px
2.选中一次时，再次滑动picker选项还没点击确定时选中值就已经自动随之变化

### Node版本

v16.17.0

**Comment by anlyyao** [comment]
我来看看～

**Comment by anlyyao** [comment]
@balabalanobala  第一个是 cell 组件的问题，已修复。 第二个是demo示例如此，不是bug， 我们的示例是绑定直接绑定了 picker 的值，所以你会看到 picker 变换选中值就更新了，你可以重新声明一个变量，以作区分。
<img width="593" alt="企业微信截图_616ffebc-1940-4868-b824-cff17ec7ad52" src="https://user-images.githubusercontent.com/51158141/196396697-a6eb8d82-4209-4be9-bed6-4777cbf6d3ec.png">
