### ISSUE TITLE
组件能否支持设置style属性用来配置组件的样式

### ISSUE THREAD

**Issue by mvpdongdong** [Tencent/tdesign-mobile-vue#426]
如题，组件能否支持设置style属性用来配置组件的样式，就像tdesign移动端h5组件就能通过给组件设置style配置组件样式

**Comment by TingShine** [comment]
指的是所有组件吗，还是特定组件？

**Comment by TingShine** [comment]
大部分组件可以通过在外层设置样式来改变组件最外层元素的样式，要定制深层的样式传参的话得结合具体的组件

**Comment by mvpdongdong** [comment]
抱歉issue提测组件库了，想给td小程序组件提issue
