### ISSUE TITLE
[PullDownRefresh] 下拉的加载图标不正常

### ISSUE THREAD

**Issue by AiyiCN** [Tencent/tdesign-mobile-vue#450]
### tdesign-mobile-vue 版本

0.13.0

### 重现链接

https://tdesign.tencent.com/mobile-vue/components/pull-down-refresh

### 重现步骤

https://tdesign.tencent.com/mobile-vue/components/pull-down-refresh
微信直接扫二维码demo，下拉刷新

### 期望结果

图标中心旋转

### 实际结果

图标被缩小了，推测是因为媒体查询缩小了图标

### 框架版本

0.13.0

### 浏览器版本

Iphone se2 微信网页

### 系统版本

Iphone se2 微信

### Node版本

实机

### 补充说明

pc浏览器模拟手机端正常(loading较大)，实机微信网页测试不正常(loading被缩小了一倍)

---------------------------------------
发现是loading组件的问题，应该是凡是有用到这个loading图标的在微信端都会变小

**Comment by anlyyao** [comment]
@AiyiCN 收到反馈 我来处理一下这个问题 。预计下周一发版带上～

**Comment by anlyyao** [comment]
应该是已经处理了 等官网同步common～
