### ISSUE TITLE
[RadioGroup] 单选框组添加方向配置选项

### ISSUE THREAD

**Issue by ion1ze** [Tencent/tdesign-mobile-vue#485]
### 这个功能解决了什么问题

在移动表单中，性别选择或者一些简单的单选框内容不需要纵向排列，是否可以添加横向排列并支持 `Cell` 包裹，方便添加 `Label`。

### 你建议的方案是什么

`RadioGroup` 组件添加横向排列支持 。

**Comment by anlyyao** [comment]
@ion1ze 感谢反馈，移动端正在做视觉升级，横向场景已在支持范围内，敬请期待～ 
<img width="791" alt="截屏2022-11-26 15 51 20" src="https://user-images.githubusercontent.com/51158141/204078478-8e22fe40-114f-4003-ae09-85eda8b7d706.png">

**Comment by LeeJim** [comment]
新增了 block 属性，将 block = false 即可。
