### ISSUE TITLE
[Button 按钮] 使用render函数渲染时按钮默认插槽中变量值变化了，但是按钮显示的内容没有变

### ISSUE THREAD

**Issue by mvpdongdong** [Tencent/tdesign-mobile-vue#487]
### tdesign-mobile-vue 版本

0.14.0

### 重现链接

https://stackblitz.com/edit/angular-2fugq1-1q2tmx?file=src%2Fdemo.vue,src%2Fmain.js,package.json

### 重现步骤

运行重现链接就会复现

### 期望结果

1. 在main.js中，把组件库切换为PC的tdesign就没有问题
2. 期望按钮默认插槽变量变化，按钮内容跟着改变

### 实际结果

render函数重新执行，按钮默认插槽的变量也变化了，但是按钮内容没有变化

### 框架版本

vue ^3.2.33

### 浏览器版本

chrome最新版

**Comment by anlyyao** [comment]
@mvpdongdong 变量用ref定义，插槽用函数的形式传递呢? 
```
setup() {
    const text = ref('文本');
    let buttonContent = '按钮内容';
    setTimeout(() => {
      text.value = '文本变化';
      buttonContent = '按钮内容变化';
    }, 3000);

    return () => {
      return h('div', [h(resolveComponent('t-button'), () => text.value)]);
    };
  },
```

**Comment by mvpdongdong** [comment]
> 

我们的业务场景是低代码平台，用户配置文本放入按钮插槽中，底层实现不会声明ref的变量来设置插槽值
