### ISSUE TITLE
[Swiper] img上的click事件无法使用

### ISSUE THREAD

**Issue by leihaoj** [Tencent/tdesign-mobile-vue#492]
### tdesign-mobile-vue 版本

0.14.1

### 重现步骤

用的是示例demo

**Comment by leihaoj** [comment]
用的是示例上的demo

**Comment by leihaoj** [comment]
pc上正常，手机端不行

**Comment by leihaoj** [comment]
你好，点击图片的上面一点可以触发但是有个报错。[Intervention] Ignored attempt to cancel a touchstart event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

**Comment by beasingleone** [comment]
> 👋 @leihaoj，感谢给 TDesign 提出了 issue。 请根据 issue 模版确保背景信息的完善，我们将调查并尽快回复你。

请文这个问题有解决吗

**Comment by anlyyao** [comment]
@beasingleone 还没，会在近期和组件升级一起处理。具体进度可看 #514 ，也欢迎一起共建～
