### ISSUE TITLE
[swiper]  在移动端轮播图里面的标签无法点击  导致 a标签跳转和点击事件无法使用，pc端正常使用，移动端无法使用

### ISSUE THREAD

**Issue by zongxingfengyun** [Tencent/tdesign-mobile-vue#499]
### tdesign-mobile-vue 版本

0.14.1

### 重现链接

https://stackblitz.com/edit/angular-twlfjc?file=package.json,src%2Fdemo.vue

### 重现步骤

需要是移动端可以重现，pc端正常

### 期望结果

可以点击

**Comment by beasingleone** [comment]
请问这个问题有解决吧。超过30天了
