### ISSUE TITLE
[t-search] @change 事件触发两次

### ISSUE THREAD

**Issue by zhao-cpu** [Tencent/tdesign-mobile-vue#506]
### tdesign-mobile-vue 版本

0.14.1

### 重现步骤

官网示例第一个和第四个@change 事件触发两次
<template>
	<t-cell-group title="基础搜索框">
		<t-search v-model="value" :clearable="true" placeholder="请输入关键字" @change="onChange"></t-search>
	</t-cell-group>
</template>

<script lang="ts" setup>
import { ref } from "vue";

const onChange = (val: string) => {
	console.log("change: ", val);
};

const value = ref("");
</script>

### 期望结果

@change事件触发一次

### 实际结果

@change事件触发两次

### 框架版本

3.2.47

### 浏览器版本

360安全浏览器

### 系统版本

Windows 10 专业版（22H2）

### Node版本

v16.17.0

**Comment by anlyyao** [comment]
@zhao-cpu 收到反馈，这边尽快处理～
