### ISSUE TITLE
[collapse-panel]  内部变量重新赋值没变化

### ISSUE THREAD

**Issue by adoer** [Tencent/tdesign-mobile-vue#512]
### tdesign-mobile-vue 版本

0.14.1

### 重现链接

https://stackblitz.com/edit/angular-82jcxq-sndqvx?file=src%2Fdemo.vue

### 如图，点击button给test重新赋值，collapse-panel 里 test 并未响应式变化
![image](https://user-images.githubusercontent.com/20873129/222306415-4d21dc94-b0b7-411c-9f9e-804aa8fdbdef.png)
参见：
https://stackblitz.com/edit/angular-82jcxq-sndqvx?file=src%2Fdemo.vue

### 期望结果

内部变量响应式变化

### 实际结果

内部变量未响应式变化

### 框架版本

Vue(3.2.33)

### 浏览器版本

Chrome(110.0.5481.178)

### 系统版本

Win10专业版(10.0.19045)

### Node版本

18.13.0

**Comment by anlyyao** [comment]
@adoer  收到反馈，这边尽快处理～
