### ISSUE TITLE
🚀 全体组件升级

### ISSUE THREAD

**Issue by anlyyao** [Tencent/tdesign-mobile-vue#514]
发布正式版本之前，需要对所有组件的视觉、交互、示例进行全新升级。

## 认领 && 贡献流程
- 评论认领组件
- 前往组件关联的 issue，查看开发指引和任务清单，
- 按任务清单对组件进行升级

#### Tips
- 每次只能认领一个组件
- 有不懂的地方可以随时联系 @leejim or @anlyyao 

> 认领方式：直接评论 “我来负责xxx组件” 即可。

## 激励

参与共建的开发者，将可以获得 [TDesign 周边](https://github.com/Tencent/tdesign/wiki/TDesign-%E5%91%A8%E8%BE%B9)（贴纸、鼠标垫、工卡套等）；

成为核心贡献者，将会拥有 TDesign 专属头像。

## 具体进展
- 优先级从上到下，当前 52  + 2个

| 所属类别 | 组件名 | 状态 | 负责人 | 关联Issue | 关联PR |
|----- | ----- | ----- | ----- | -----| -----|
| 输入 | Table 表格（New）    | 🔵 已完成 | @anlyyao | -  | #740
| 输入 | Form 表单 （New）   | 🔵 已完成 | @anlyyao| - | #591 
| 输入 | Checkbox 复选框    | 🔵 已完成 | @jarmywang  |- | #519
| 输入 | DateTimePicker 时间选择器   | 🔵 已完成 | @LeeJim  | - |#556
| 输入 | Input 输入框   | 🔵 已完成 | @ccccpj  | - | #531 
| 输入 | Picker 选择器   | 🔵 已完成 | @LeeJim  | - | #539 
| 输入 | Radio 单选框   | 🔵 已完成 | @LeeJim | - | #517 
| 输入 | Rate 评分   | 🔵 已完成 | @fengchunqi | - | #582 
| 输入 | Search 搜索框   | 🔵 已完成 | @anlyyao | - |#540
| 输入 | Slider 滑动选择器   | 🔵 已完成 | @anlyyao | - |#610 
| 输入 | Stepper 步进器   | 🔵 已完成 | @anlyyao | - | #518 
| 输入 | Switch 开关   | 🔵 已完成 | @LeeJim | - | #520
| 输入 | Textarea 多行文本框   | 🔵 已完成 | @anlyyao | - |#523 
| 输入 | Upload 上传   | 🔵 已完成 | @LeeJim  | - |#587 
| 输入 | Cascader 级联选择器 | 🔵 已完成 | @anlyyao |- | #533 
| 输入 | Calendar 日历 | 🔵 已完成 | @ccccpj  | - |#579 
| 数据展示 | Avatar 头像   | 🔵 已完成 | @ccccpj  | - | #631 
| 数据展示 | Badge 徽标   | 🔵 已完成 | @jarmywang  | - |#576 
| 数据展示 | Cell 单元格   | 🔵 已完成 | @LeeJim | - |#529
| 数据展示 | Collapse 折叠面板   | 🔵 已完成 | @LeeJim | #623 | #666
| 数据展示 | CountDown 倒计时    | 🔵 已完成 | @anlyyao | - |#614 
| 数据展示 | DropdownMenu 下拉菜单   | 🔵 已完成 | @ccccpj  | #634  |-
| 数据展示 | Empty 空内容 （New）  | 🔵 已完成 | @mamumu123 | - |#538 
| 数据展示 | Result 结果   | 🔵 已完成 | @mamumu123 | - |#543 
| 数据展示 | Footer 页脚  （New） | 🔵 已完成 | @mamumu123 | - |#525 
| 数据展示 | Progress 进度条   | 🔵 已完成 | @anlyyao | - | #640
| 数据展示 | Grid 宫格   | 🔵 已完成 | @LeeJim  | - | #584
| 数据展示 | Image 图片   | 🔵 已完成 | @LeeJim  | - | #561
| 数据展示 | ImageViewer 图片预览   | 🔵 已完成 | @leejim | #624  | #677
| 数据展示 | Skeleton 骨架屏    | 🔵 已完成 | @anlyyao | - | #557 
| 数据展示 | Sticky 吸顶容器   | 🔵 已完成 | @anlyyao | - | #555
| 数据展示 | Swiper 轮播图   | 🔵 已完成 | @yaogengzhu  | - | -
| 数据展示 | Tag 标签   | 🔵 已完成 | @yaogengzhu | - | #615 
| 基础 | Button 按钮   | 🔵 已完成 | @LeeJim   | - | #612
| 基础 | Divider 分割线   | 🔵 已完成 | @jarmywang | - | #600 
| 基础 | Fab 悬浮按钮    | 🔵 已完成 | @LeeJim  | - | #618
| 基础 | Link 链接 （New） | 🔵 已完成 | @brianzhang | - | #589 
| 导航 | Drawer 抽屉   | 🔵 已完成 | @LeeJim | - | #673
| 导航 | Indexes 索引   | 🔵 已完成 | @yaogengzhu | #636  | -
| 导航 | Navbar 导航栏   | 🔵 已完成 | @Charles-1999 | #632  | #669 
| 导航 | Steps 步骤条   |  🔵 已完成 | @yaogengzhu  | #635  | #660
| 导航 | TabBar 标签栏   | 🔵 已完成 | @jarmywang  | - | #633 
| 导航 | Tabs 选项卡   | 🔵 已完成 | @TeacherDingTing  | - | #639 
| 消息提醒 | ActionSheet 动作面板   | 🔵 已完成 | @brianzhang | - | #637 
| 消息提醒 | BackTop 返回顶部   | 🔵 已完成 | @nined9  | - | #641 
| 消息提醒 | Dialog 对话框   | 🔵 已完成 | @tangzixuan  | - | #564 
| 消息提醒 | Loading 加载   | 🔵 已完成 | @LeeJim | - | #528
| 消息提醒 | Message 消息通知   | 🔵 已完成 | @yusuf-yz  | - | #548 
| 消息提醒 | NoticeBar 消息通知   |🔵 已完成 | @yaogengzhu  | #622  | #654
| 消息提醒 | Overlay 遮罩层   | 🔵 已完成 | @LeeJim  | - | #604
| 消息提醒 | Popup 弹出层   | 🔵 已完成 | @LeeJim  | - | #605
| 消息提醒 | PullDownRefresh 下拉刷新   |  🔵 已完成 | @anlyyao | #625  | #644
| 消息提醒 | SwipeCell 滑动操作   | 🔵 已完成 | @nined9  | #630 | #663
| 消息提醒 | Toast 轻提示 | 🔵 已完成 | @mistakers | - | #611  

### 3.1 - 3.3
- 引入 新的样式 token

### 3.11 - 3.17

- 表单类组件开始进入开发

- 3 完成开发，4 开发中，进度 5%

### 3.18 - 3.24

- 6 完成开发，11 开发中，进度 11%

### 3.25 - 4.3
- 12 完成开发，5 CR中，4 开发中，进度 23%

### 4.4 - 4.7
- 17 完成开发，5 CR中，4 开发中，进度 32%

### 4.8 - 4.14
- 20 完成开发，5 CR中，4 开发中，进度 37%

### 4.15 - 4.21
- 29 完成开发， 5 CR中，3 进行中，进度 53%

###  4.22 - 5.5 
- 35 完成开发， 8 CR中，7 未认领，进度 64%

###  5.6 - 5.12
- 40 完成开发， 6 CR中，6 进行中，2 未认领，进度 74%

###  5.13 - 5.19
- 49 完成开发， 4 进行中，1 未认领，进度 90%

###  5.20 - 5.26
- 51 完成开发， 1 CR中，2 进行中，进度 94%

**Comment by LeeJim** [comment]
认领 radio

**Comment by jarmywang** [comment]
认领 Checkbox

**Comment by mamumu123** [comment]
认领 Footer

**Comment by LeeJim** [comment]
认领 switch

**Comment by LeeJim** [comment]
认领 loading

**Comment by tangzixuan** [comment]
jerimizhang 认领Dialog

**Comment by yaogengzhu** [comment]
认领Tag 标签

**Comment by anlyyao** [comment]
认领 Cascader

**Comment by LeeJim** [comment]
认领 picker

**Comment by yusuf-yz** [comment]
认领 Message 消息通知

**Comment by mistakers** [comment]
认领 Toast 消息通知

**Comment by mamumu123** [comment]
认领 result

**Comment by tomcat-hz** [comment]
认领 avatar

**Comment by LeeJim** [comment]
认领 image

**Comment by jarmywang** [comment]
认领 Badge

**Comment by brianzhang** [comment]
认领Links

**Comment by LeeJim** [comment]
认领grid

**Comment by LeeJim** [comment]
认领 popup、overlay

**Comment by jarmywang** [comment]
认领 Divider

**Comment by brianzhang** [comment]
认领:ActionSheet

**Comment by anlyyao** [comment]
认领 CountDown

**Comment by LeeJim** [comment]
认领 fab

**Comment by anlyyao** [comment]
认领 progress

**Comment by nined9** [comment]
认领 BackTop

**Comment by jarmywang** [comment]
认领 TabBar

**Comment by yaogengzhu** [comment]
认领 NoticeBar

**Comment by TeacherDingTing** [comment]
认领tabs

**Comment by nined9** [comment]
认领 SwiperCell

**Comment by anlyyao** [comment]
认领 pull-down-refresh

**Comment by yaogengzhu** [comment]
认领Steps

**Comment by yaogengzhu** [comment]
认领 Indexes

**Comment by yaogengzhu** [comment]
认领 Swiper

**Comment by LeeJim** [comment]
已完成

**Comment by anlyyao** [comment]
感谢大家的支持，组件升级及测试覆盖率提升任务均已完成，TDesign Mobile Vue 于2023.6.27发布1.0.0-rc，后续我们会对单个组件进行排查和特性增强，向1.0.0前进～

PS: 目前我们的激励方式是积分兑换，每个季度结算一次，另外只要成功参与贡献就能获得证书。具体规则在这里哈https://github.com/Tencent/tdesign/discussions/339。
