### ISSUE TITLE
Textarea组件数字统计不显示

### ISSUE THREAD

**Issue by QQOQ** [Tencent/tdesign-mobile-vue#547]
### tdesign-mobile-vue 版本

0.16.0

### 重现步骤

在0.16.0版本的Textarea组件不显示统计输入的数字

**Comment by anlyyao** [comment]
@QQOQ 贴一下代码片段？
我看官网是正常的
<img width="394" alt="截屏2023-04-03 14 52 30" src="https://user-images.githubusercontent.com/51158141/229433083-e333f8ff-66b0-452d-9fcc-7ea6434bac6c.png">

**Comment by QQOQ** [comment]
> @QQOQ 贴一下代码片段？ 我看官网是正常的 <img alt="截屏2023-04-03 14 52 30" width="394" src="https://user-images.githubusercontent.com/51158141/229433083-e333f8ff-66b0-452d-9fcc-7ea6434bac6c.png">

文档不完整，看了代码找到了，加上indicator就行了
