### ISSUE TITLE
[-] 编译出错误

### ISSUE THREAD

**Issue by williambao** [Tencent/tdesign-mobile-vue#575]
### tdesign-mobile-vue 版本

0.17.0

### 重现步骤

安装了0.17.0版本后， 貌似编译不通过了。 库里用了@相对路径？
run的时候没有从库目录下找config和shared， 而是从我项目根目录去找。

![CleanShot 2023-04-09 at 19 40 38@2x](https://user-images.githubusercontent.com/779521/230770514-e24ab913-3f6a-452c-9bf8-761919ce0729.png)

**Comment by LeeJim** [comment]
我来处理下
