### ISSUE TITLE
[indexes] 文档缺失

### ISSUE THREAD

**Issue by steven12138** [Tencent/tdesign-mobile-vue#58]
### tdesign-mobile-vue 版本

0.8

### 重现链接

https://tdesign.tencent.com/mobile-vue/components/indexes

### 重现步骤

说明文档indexes缺失
打开自动返回组件概览页面

https://tdesign.tencent.com/mobile-vue/components/indexes

### 期望结果

添加indexes文档

### 实际结果

文档缺失

**Comment by Dengzygx** [comment]
我这边处理一下

**Comment by Dengzygx** [comment]
已处理

**Comment by Dengzygx** [comment]
组件概览中暂时下掉indexes组件，等待组件走查完毕后，同步更新组件概览和左侧菜单栏
