### ISSUE TITLE
[SLOT API] API 尤其是涉及到 icon 属性的组件可否统一输入值

### ISSUE THREAD

**Issue by insub** [Tencent/tdesign-mobile-vue#593]
### 这个功能解决了什么问题

以最常用的Button 组件为例，如果需要设置 icon 属性：
tdesign-mobile-vue 的 button api 的 icon 属性接受的类型是：Slot / Function
tdesign-miniprogram 的 button api 的 icon 属性接受的类型是：String / Object
*.* ....

### 你建议的方案是什么

希望各组件的 icon 属性能够统一兼容 string 类型，使用最简单，同时建议各端的接口能够尽量保持一致
作为前端希望能用 Tdesign 作为开发的基础框架，无论是小程序，App，H5 还是 Web，各端接口总有些很常用的但有互不兼容的差异的话切换项目的时候太难受了

**Comment by LeeJim** [comment]
感谢反馈，你说的问题确实是存在的，但这里是因为底层的差别导致的妥协方案。

小程序的 icon 目前不支持 svg 只能用 font 来实现，因此使用 font 的话就会全量加载图标，就不存在按需引用图标的可能性了。所以在小程序里，为了让用户方便，就内嵌了所有图标，也就出现了支持 string 的图标属性。

而 vue/react，可以使用 svg，可以按需引用，为了更好的性能，大家都倾向于按需引用的。全量引用组件固然方便，但带来的冗余也是巨大的。

早期的组件库的设计都是小程序那样，支持通过 string 类型来使用图标，但渐渐的都改成插槽的方式。这也是我们的最终方案。

当然，如果为了方便，你可以二次封装，对这些插槽做string类型的封装。因为 icon 时是支持全量引入的：

```
<icon name="check-circle-filled" />
```
