### ISSUE TITLE
[ImageViewer] 图片预览组件缺少手势缩放功能、预览图片惰性加载

### ISSUE THREAD

**Issue by jys125773** [Tencent/tdesign-mobile-vue#60]
### 这个功能解决了什么问题

1.对应一个图片预览组件，支持图片缩放查看是不可缺少的功能；
2.还有就是引用该组件后，即使没有打开预览，也会组件加载所有的dom结构，并且高清图的请求会占用网络带宽甚至影响页面加载速度；
3.组件元素的类名，有些事直接以image-viewer开头，而有些是t-image-viewer

### 你建议的方案是什么

1.支持图片缩放查看预览；
2.支持组件元素惰性加载；
3.组件元素的类名统一以t-image-viewer前缀

**Comment by Dengzygx** [comment]
感谢反馈，我这边处理一下~
