### ISSUE TITLE
移动端date-time-picker 组件面对不同尺寸的屏幕时，时间选择样式有问题

### ISSUE THREAD

**Issue by yzy163414** [Tencent/tdesign-mobile-vue#602]
### tdesign-mobile-vue 版本

0.17.0-beta

### 重现步骤

<template>
  <t-popup v-model="visible" close-on-overlay-click placement="bottom">
    <div class="select-start-time">
      <t-date-time-picker
        v-model:value="pickerValue"
        :mode="isTimePicker ? [null, 'minute'] : ['date']"
        title="选择日期"
        :format="isTimePicker ? 'HH:mm' : 'YYYY-MM-DD'"
        @confirm="onConfirm"
        @cancel="onCancel"
      />
    </div>
  </t-popup>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import dayjs from 'dayjs';
import { isPC } from '@/util';
// 接收父组件传值
const props = defineProps({
  visible: {
    type: Boolean,
    default: false,
  },
  // 开始时间
  startTime: {
    type: String,
    default: '',
  },
  isTimePicker: {
    type: Boolean,
    default: false,
  },
});

watch(
  () => props.startTime,
  () => {
    // 如果传入startTime存在显示传入的日期
    if (props.startTime) {
      pickerValue.value = props.startTime;
    } else if (!props.isTimePicker && isPC()) {
      // 否则显示当前日期
      pickerValue.value = dayjs(new Date()).format('YYYY-MM-DD');
    }
  },
);

const emits = defineEmits<{
  (e: 'update:visible', value: boolean): void; // 无需在父组件注册update:visible
  (e: 'startTimeConfirm', value: String): void;
}>();

const visible = computed({
  get: () => props.visible,
  set: (value) => emits('update:visible', value),
});

// 日期选中绑定值
const pickerValue = ref('');

// 点击确认按钮触发
const onConfirm = (value) => {
  pickerValue.value = value;
  emits('startTimeConfirm', pickerValue.value);
};

// 点击取消按钮触发
const onCancel = () => {
  emits('update:visible', false);
};
</script>

<style scoped lang="less">
.select-start-time {
  height: 248px;
  background: #fff;
}
.pc-mode {
  padding: 32px;
  width: 400px;
  height: 400px;
  background-color: white;
}
</style>

### 期望结果

![image](https://user-images.githubusercontent.com/73727184/232652179-a3b92d6e-4afa-442c-8ac2-5894f6abd192.png)

无论界面宽度如何变化时，时间选择样式不发生改变
![image](https://user-images.githubusercontent.com/73727184/232652368-b99d1837-8239-40a0-be7f-76424b68d97d.png)

### 实际结果

![image](https://user-images.githubusercontent.com/73727184/232652381-18655bbf-9f4e-44b5-85a8-e2193a682646.png)

### 框架版本

Vue(3.2.47)

### 浏览器版本

Chrome版本 112.0.5615.86（正式版本） （64 位）

### 系统版本

windows11

### Node版本

v16.20.0

### 补充说明

0.17.0-beta版本内date-time-picker 组件默认值default-value也无法使用

**Comment by yzy163414** [comment]
这个缺陷多久能处理啊？？？

**Comment by yzy163414** [comment]
都大半个月了，还没做处理吗？

**Comment by anlyyao** [comment]
@yzy163414 你好 我这边直接在用官网示例，chrom打开，缩放宽度未能复现样式上的问题，我应该群内有回复您，请问后面升级之后问题还在吗？

**Comment by yzy163414** [comment]
哦，没事，问题已经解决了&nbsp;


?学长
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月19日(星期五) 下午2:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tencent/tdesign-mobile-vue] 移动端date-time-picker 组件面对不同尺寸的屏幕时，时间选择样式有问题 (Issue #602)





 
@yzy163414 你好 我这边直接在用官网示例，chrom打开，缩放宽度未能复现样式上的问题，我应该群内有回复您，请问后面升级之后问题还在吗？
