### ISSUE TITLE
【Indexes组件升级】任务单

### ISSUE THREAD

**Issue by anlyyao** [Tencent/tdesign-mobile-vue#636]
> 我们最终的目标是希望mobile vue、mobile react、miniprogram **三端可以共用一套样式文件、一套示例文档**，而目前 miniprogram 端的完成度最高，因此在做组件升级时，我们需要和小程序端的同名组件保持一样的 DOM结构，以复用一套样式，组件示例文件命名也应和小程序端命名保持一致，以复用一套示例文档。

## 开发指引
[mobile vue：组件升级指引](https://github.com/Tencent/tdesign-mobile-vue/wiki/mobile-vue%EF%BC%9A%E7%BB%84%E4%BB%B6%E5%8D%87%E7%BA%A7%E6%8C%87%E5%BC%95)

## 任务清单
- [ ] DOM 结构对齐小程序端
- [ ] 改用 V2文件夹下样式
- [ ] Indexes 中 height 属性废弃
- [ ] Indexes中 list 属性更名为 indexList 属性
- [ ] Indexes 新增 change 事件
- [ ] IndexesAnchor 新增 index 属性
- [ ] 官网示例对齐新视觉稿

## 组件新视觉
> 设计稿：【腾讯 CoDesign】TDesign移动端设计稿](https://codesign.qq.com/s/RG6X0kXNObZxEPB)

#### 新视觉样式如下：
<div style="display:flex">
<img width="33%" alt="Indexes 索引  移动端展示01" src="https://user-images.githubusercontent.com/51158141/234218466-48df1eac-e088-43b0-91d5-cadff8ac2069.png">
<img width="33%" alt="Indexes 索引  移动端展示02" src="https://user-images.githubusercontent.com/51158141/234218471-36246582-ca19-4d1c-970f-08a6b8220095.png">
<img width="33%" alt="Indexes 索引  移动端展示03" src="https://user-images.githubusercontent.com/51158141/234218480-1c8e4c55-7507-4d7c-894d-b28f1cdc7693.png">
</div>

## 激励
参与共建的开发者，将可以获得 [TDesign 周边](https://github.com/Tencent/tdesign/wiki/TDesign-%E5%91%A8%E8%BE%B9)（贴纸、鼠标垫、工卡套等）；

成为核心贡献者，将会拥有 TDesign 专属头像。

**Comment by yaogengzhu** [comment]
@yaogengzhu

**Comment by yaogengzhu** [comment]
- [x] DOM 结构对齐小程序端
- [x] 改用 V2文件夹下样式
- [x] Indexes 中 height 属性废弃
- [x] Indexes中 list 属性更名为 indexList 属性
- [x] Indexes 新增 change 事件
- [x] IndexesAnchor 新增 index 属性
- [x] 官网示例对齐新视觉稿
