### ISSUE TITLE
[Icon] 支持下<t-icon> 方式的使用

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-mobile-vue#652]
### 这个功能解决了什么问题

简便

### 你建议的方案是什么

参考tdesign web

**Comment by Jiachang-Cai** [comment]
> t-icon 是单独的一个包，你也可以直接这么用

不行啊 mobile 里面

**Comment by anlyyao** [comment]
> > t-icon 是单独的一个包，你也可以直接这么用
> 
> 不行啊 mobile 里面

我懂你什么意思了 我在mobile vue 端上补充一个TIcon，下周发版带上～
