### ISSUE TITLE
[Input] clearable prefixIcon suffixIcon 都不是在input内的是否合理

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-mobile-vue#653]
### 这个功能解决了什么问题

提高体验
<img width="462" alt="image" src="https://user-images.githubusercontent.com/8606851/236399685-5a720427-dd73-485f-bf68-cca79217c4cf.png">
tdesign web
<img width="510" alt="image" src="https://user-images.githubusercontent.com/8606851/236399737-19dc15be-8c91-41cc-9988-9bcb0f8eeb2c.png">

### 你建议的方案是什么

参考tdesign web

**Comment by anlyyao** [comment]
@Jiachang-Cai pc端如下，input 也是完全独立的～
<img width="1239" alt="截屏2023-05-06 12 48 22" src="https://user-images.githubusercontent.com/51158141/236600542-af71a793-cee2-43a6-b1c3-cb428ec5254f.png">

**Comment by LeeJim** [comment]
这个问题和设计师反馈下，看如何优化

**Comment by RADWIMPS426** [comment]
> ### 这个功能解决了什么问题
> 提高体验 <img alt="image" width="462" src="https://user-images.githubusercontent.com/8606851/236399685-5a720427-dd73-485f-bf68-cca79217c4cf.png"> tdesign web <img alt="image" width="510" src="https://user-images.githubusercontent.com/8606851/236399737-19dc15be-8c91-41cc-9988-9bcb0f8eeb2c.png">
> 
> ### 你建议的方案是什么
> 参考tdesign web

你框选橙色的位置是文字的输入范围，不是input的范围
