### ISSUE TITLE
升级到0.20.0版本后，启动项目报错，貌似与'@/shared'有关

### ISSUE THREAD

**Issue by ZS1994** [Tencent/tdesign-mobile-vue#659]
### tdesign-mobile-vue 版本

0.20.0

### 重现步骤

![image](https://github.com/Tencent/tdesign-mobile-vue/assets/20389909/f333b4c7-ae04-4436-a8f3-6af518204c1f)
![image](https://github.com/Tencent/tdesign-mobile-vue/assets/20389909/2816fbc4-8f50-4163-a58e-26ada734a3d2)
启动就报这个错，这是咋回事呀，看起来是比之前老版本多增加了依赖shared组件，但是我本地是没有这个文件的呀，另外这个文件是干嘛的啊，该如何解决这个问题😭😭😭😭

### 框架版本

3.2.33

**Comment by anlyyao** [comment]
@ZS1994 已定位到问题，今天处理完毕～
