### ISSUE TITLE
移动端适配暗黑模式

### ISSUE THREAD

**Issue by a77uu** [Tencent/tdesign-mobile-vue#667]
### 这个功能解决了什么问题

解决在多端场景下，过渡后仍能保持不同页面下主题相同。

### 你建议的方案是什么

能够和桌面端对齐，允许配置暗黑模式。
## IssueShoot
- 预估时长: 5
- 期望完成时间: 2023-07-10 00:00:00 +0000 UTC
- 开发难度: 高
- 参与人数: 1
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by LeeJim** [comment]
token正在梳理中，很快就可以支持了
