### ISSUE TITLE
npm 0.22.0，引入报错

### ISSUE THREAD

**Issue by insub** [Tencent/tdesign-mobile-vue#688]
### tdesign-mobile-vue 版本

^0.22.0

### 重现步骤

从 0.17 升级到 0.22，npm 安装无问题，安装完成后启动项目时报错如下：

补充： 0.21.0 无此问题

X [ERROR] [plugin vite:dep-pre-bundle] Cannot find module 'D:/Sites/yeqiu-h5/shared/useClickAway' from 'D:\Sites\yeqiu-h5\node_modules\tdesign-mobile-vue\es\swipe-cell\index.js'
00:32:00.921     ../../../../Sites/yeqiu-h5/node_modules/tdesign-mobile-vue/es/swipe-cell/index.js:19:7:
00:32:00.926       19 │ import '@/shared/useClickAway';
00:32:00.927          ╵        ~~~~~~~~~~~~~~~~~~~~~~~
00:32:04.173 X [ERROR] [plugin vite:dep-pre-bundle] Cannot find module 'D:/Sites/yeqiu-h5/shared' from 'D:\Sites\yeqiu-h5\node_modules\tdesign-mobile-vue\es\swipe-cell\index.js'
00:32:04.174     ../../../../Sites/yeqiu-h5/node_modules/tdesign-mobile-vue/es/swipe-cell/index.js:23:7:
00:32:04.180       23 │ import '@/shared';
00:32:04.186          ╵        ~~~~~~~~~~

### 期望结果

希望无报错

**Comment by anlyyao** [comment]
@insub 这里马上处理一下，补一个 beta版本
