### ISSUE TITLE
[list列表]组件下拉刷新demo报错无法使用

### ISSUE THREAD

**Issue by zhangpinguknow2** [Tencent/tdesign-mobile-vue#75]
### tdesign-mobile-vue 版本

"tdesign-mobile-vue@0.8.3-alpha.2"

### 重现步骤

https://tdesign.tencent.com/mobile-vue/components/list?tab=demo  直接点闪电运行代码就不行

**Comment by Dengzygx** [comment]
收到，我们这边更新一下demo代码

**Comment by Dengzygx** [comment]
问题已修复，版本为0.8.4

**Comment by zhangpinguknow2** [comment]
收到，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月15日(周五) 下午5:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Tencent/tdesign-mobile-vue] [list列表]组件下拉刷新demo报错无法使用 (Issue #75)




 
问题已修复，版本为0.8.4
