### ISSUE TITLE
[BackTop] 显示消失过渡；深色样式调整

### ISSUE THREAD

**Issue by pageee1021** [Tencent/tdesign-mobile-vue#758]
### tdesign-mobile-vue 版本

最新版

### 重现步骤

1、显示消失能否增加一些不透明度渐变，过渡自然一些
2、设计调整-深色样式增加了描边，详见设计稿：https://www.figma.com/file/jivYXTMTP3jEkeZXWbMh4J/TDesign-for-mobile?type=design&node-id=26631-6366&t=PSxHL1IjsGUuLp7W-4

**Comment by anlyyao** [comment]
@pageee1021 
问题1: 属于组件特性，后期补充
问题2: 描边样式修复在 https://github.com/Tencent/tdesign-common/pull/1367
