### ISSUE TITLE
[Indexes] demo返回方式

### ISSUE THREAD

**Issue by pageee1021** [Tencent/tdesign-mobile-vue#760]
### tdesign-mobile-vue 版本

最新版

### 重现步骤

这里可以不用增加按钮用于返回，直接用导航左上角的返回就好
<img width="479" alt="image" src="https://github.com/Tencent/tdesign-mobile-vue/assets/94840745/d710954e-c992-42b9-86c0-f74184516512">

**Comment by anlyyao** [comment]
@pageee1021 这里是因为模拟器上的返回按钮默认返回主页，非受控，所以indexes在示例上新增了一个返回按钮的样式～ 囧
