### ISSUE TITLE
[Tabs] 字号问题

### ISSUE THREAD

**Issue by pageee1021** [Tencent/tdesign-mobile-vue#762]
### tdesign-mobile-vue 版本

最新版

### 重现步骤

1、字号问题
默认尺寸字号应为@font-size-markMedium:14px 和 @font-size-bodyMedium:14px
大尺寸字号应为@font-size-markLarge:16px 和 @font-size-bodyLarge:16px
<img width="341" alt="image" src="https://github.com/Tencent/tdesign-mobile-vue/assets/94840745/80bd0368-5667-486b-8765-2d70851d7a67">

2、图标尺寸优化
大尺寸匹配的图标尺寸调整为20*20px，详见设计稿：https://www.figma.com/file/4SdclZkcv5bPgX6pa8AsmI/Demo-%E7%A7%BB%E5%8A%A8%E7%AB%AF%E5%B1%95%E7%A4%BA-%26-%E4%BA%A4%E4%BA%92-%26-%E6%96%B0%E5%A2%9E%E7%BB%84%E4%BB%B6?type=design&node-id=27382-26465&t=DUs6fFELRQmn8Zg5-4

**Comment by anlyyao** [comment]
@pageee1021 字号问题已处理在 [#11386](https://github.com/Tencent/tdesign-common/pull/1386)， 当前tabs未支持icon属性，等后续补齐该属性后再处理问题2
