### ISSUE TITLE
【style】基础样式发布的时候似乎没有构建引入

### ISSUE THREAD

**Issue by yanceyou** [Tencent/tdesign-mobile-vue#778]
### tdesign-mobile-vue 版本

v0.23.0

### 补充说明

构建产物下， es/esm/lib 下均没有成功把 src/style/index.js 构建出包含 @import 路径下的样式。

**Comment by anlyyao** [comment]
@yanceyou 是指 reset.css 吗？

**Comment by anlyyao** [comment]
@yanceyou 产物都是编译后的，这里构建并没有问题哈。 如果是问那一套CSS自定义属性（变量）的导出问题，会在后面支持暗黑模式后一并支持。
