### ISSUE TITLE
[Input] demo类型还原以及设计对齐调整

### ISSUE THREAD

**Issue by pageee1021** [Tencent/tdesign-mobile-vue#784]
### tdesign-mobile-vue 版本

最新版

### 重现步骤

demo页设计稿：https://www.figma.com/file/4SdclZkcv5bPgX6pa8AsmI/Demo-%E7%A7%BB%E5%8A%A8%E7%AB%AF%E5%B1%95%E7%A4%BA-%26-%E4%BA%A4%E4%BA%92-%26-%E6%96%B0%E5%A2%9E%E7%BB%84%E4%BB%B6?type=design&node-id=28591-38235&t=DUs6fFELRQmn8Zg5-4

1、增加必填的类型
2、设计调整：所有标签与内容保持上对齐
<img width="358" alt="image" src="https://github.com/Tencent/tdesign-mobile-vue/assets/94840745/f18f5386-114e-466e-8918-b646c67aa7b6">
3、带按钮的按钮尺寸有误，且输入框高度应固定
<img width="391" alt="image" src="https://github.com/Tencent/tdesign-mobile-vue/assets/94840745/0866868d-3606-4841-88af-f71ee7795ff0">
4、竖排样式请使用左对齐
<img width="455" alt="image" src="https://github.com/Tencent/tdesign-mobile-vue/assets/94840745/25191878-c3bc-491d-9de3-1fabf9071dee">
5、标签外置样式底部间距小
<img width="373" alt="image" src="https://github.com/Tencent/tdesign-mobile-vue/assets/94840745/bc1f4e1c-8fe0-490f-bc82-dea9fede10ba">

**Comment by anlyyao** [comment]
认领
