### ISSUE TITLE
[Toast] 背景色更改为Font Gy1 90%

### ISSUE THREAD

**Issue by pageee1021** [Tencent/tdesign-mobile-vue#802]
### tdesign-mobile-vue 版本

最新版

### 重现步骤

背景均改为Font Gy1 90% 详见设计稿
https://www.figma.com/file/4SdclZkcv5bPgX6pa8AsmI/Demo-%E7%A7%BB%E5%8A%A8%E7%AB%AF%E5%B1%95%E7%A4%BA-%26-%E4%BA%A4%E4%BA%92-%26-%E6%96%B0%E5%A2%9E%E7%BB%84%E4%BB%B6?type=design&node-id=25169-19856&t=pgfgxItnysNnh2M2-4

**Comment by anlyyao** [comment]
@pageee1021 目前 overlay 和 toast 组件背景色都改成 font gy1之后，当toast和overlay组合使用，两个背景色会融合，这里是需要单独处理还是？？
