### ISSUE TITLE
[文档] 导航栏高亮bug

### ISSUE THREAD

**Issue by mk965** [Tencent/tdesign-mobile-vue#82]
### tdesign-mobile-vue 版本

yes

### 重现链接

https://tdesign.tencent.com/mobile-vue/components/divider

### 重现步骤

点击左侧导航栏

### 期望结果

当前点击打开的页面高亮

### 实际结果

上一个打开的页面高亮

### 补充说明

![image](https://user-images.githubusercontent.com/30465793/163904967-09fe6206-3bbd-4b01-ad00-0917f282432d.png)

**Comment by HQ-Lin** [comment]
更新一下 tdesign-site-components@0.9.8

**Comment by Dengzygx** [comment]
问题已解决
