### ISSUE TITLE
[Steps] 当有标题文本换行和不换行同时存在时，步骤图标没有对齐

### ISSUE THREAD

**Issue by huangpiqiao** [Tencent/tdesign-mobile-vue#835]
### tdesign-mobile-vue 版本

0.24.0

### 重现链接

https://stackblitz.com/edit/sfvbmn?file=src%2Fdemo.vue

### 重现步骤

步骤标题设置很长和很短同时存在

![wecom-temp-1033616-cfb3f9d2f5f02e58adb46b1f81efb938](https://github.com/Tencent/tdesign-mobile-vue/assets/16223845/84bb4c4d-855c-47d4-8069-7a82c80643a9)

### 期望结果

步骤图标和文本能对齐

### 实际结果

步骤图标和文本不对齐

**Comment by Resuragam** [comment]
可以试试深度选择器，好像可以解决这个问题。
![image](https://github.com/Tencent/tdesign-mobile-vue/assets/81508939/ad0b285a-f233-4551-aa2b-d3f3a9c95c2f)
![image](https://github.com/Tencent/tdesign-mobile-vue/assets/81508939/234cccd5-c710-4d94-884a-502d88f1de92)
