### ISSUE TITLE
[swiper] 没有支持loop这个功能吧?

### ISSUE THREAD

**Issue by dufemeng** [Tencent/tdesign-mobile-vue#84]
### tdesign-mobile-vue 版本

0.8.4

**Comment by MarvenGong** [comment]
目前是支持loop的呢，可以无限向一个方向滑动

**Comment by MarvenGong** [comment]
明白您的意思了。是说无法通过loop: false 来关闭循环对吧

**Comment by dufemeng** [comment]
对滴



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月24日(周日) 下午2:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Tencent/tdesign-mobile-vue] [swiper] 没有支持loop这个功能吧? (Issue #84)




 
明白您的意思了。是说无法通过loop: false 来关闭循环对吧

**Comment by MarvenGong** [comment]
已处理，请更新至最新版本
