### ISSUE TITLE
[date-time-picker] onColumnChange 事件返回的数据有误 

### ISSUE THREAD

**Issue by dufemeng** [Tencent/tdesign-mobile-vue#91]
### tdesign-mobile-vue 版本

0.8.4

### 重现步骤

<img width="1909" alt="截屏2022-04-28 16 13 54" src="https://user-images.githubusercontent.com/10006784/165708437-c9da75cc-0907-49b8-a92d-cd7f74cf322c.png">

### 实际结果

const onColumnChange = ({ value, index }) => {
      context.emit('columnChange', {
        value,
        index,
      });
    };

**Comment by Dengzygx** [comment]
已处理
