### ISSUE TITLE
Search 搜索框组件在ios设备上显示出两个搜索icon

### ISSUE THREAD

**Issue by Jin-da** [Tencent/tdesign-mobile-vue#935]
### tdesign-mobile-vue 版本

是

### 重现步骤

Search 搜索框组件在ios设备上显示出两个搜索[icon](https://7265-re01-3g7r52nq092d0c3c-1312605588.tcb.qcloud.la/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20230706174849.jpg?sign=f14ea3f6ceee5de106f18cf3fb3fcb90&t=1688636955)

### Node版本

v18.16.0

**Comment by anlyyao** [comment]
@Jin-da 版本号是多少？

**Comment by Jin-da** [comment]
tdesign-mobile-vue@1.0.0-rc.1

**Comment by anlyyao** [comment]
> tdesign-mobile-vue@1.0.0-rc.1

https://stackblitz.com/run?file=package.json

我这边复现不出，方便在提供一下 iOS 版本？或者真机型号？

**Comment by Jin-da** [comment]
真机 ios11pro 版本16.5.1

**Comment by yaogengzhu** [comment]
可以录制一个视频看下异常情况，或者截图

**Comment by Jin-da** [comment]
[https://7265-re01-3g7r52nq092d0c3c-1312605588.tcb.qcloud.la/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20230706174849.jpg?sign=a488ef7d50e6e49b5b9ae7c3aee2eca4&t=1688951955](url)

**Comment by yaogengzhu** [comment]
可以直接把图拖到评论框，你这图打不开勒。🤣

**Comment by Jin-da** [comment]
![微信图片_20230706174849](https://github.com/Tencent/tdesign-mobile-vue/assets/69777107/cd5c883a-b09d-436c-8629-0d98f15ee83e)
🤣

**Comment by 1943715762** [comment]
请问改好了吗？我出现类似问题了，后面两个X。 
![1715246406430](https://github.com/Tencent/tdesign-mobile-vue/assets/55580893/cc20b0ea-e5ce-4ac7-8cff-37f5fe240989)

**Comment by Jin-da** [comment]
> 请问改好了吗？我出现类似问题了，后面两个X。 ![1715246406430](https://private-user-images.githubusercontent.com/55580893/329439875-cc20b0ea-e5ce-4ac7-8cff-37f5fe240989.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMDkyNzgsIm5iZiI6MTcxNTMwODk3OCwicGF0aCI6Ii81NTU4MDg5My8zMjk0Mzk4NzUtY2MyMGIwZWEtZTVjZS00YWM3LThjZmYtMzdmNWZlMjQwOTg5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDAyNDI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwYTJjZDBlZjRhMGU1ZDA4NWVmMTcxMGNjNjg4ZTNmZDFmOTc2NGRjYzQyOTRlMDgxMjE5YjFmZGEyOTRkYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hQCvwnfjGfsuqtUfaL1OTm4g-7VsqspBciuNon15NSw)

如果新版本有这个问题的话 建议开个新的issue 这个已经关闭了
