### ISSUE TITLE
未知的 HTML 标记

### ISSUE THREAD

**Issue by Oniokey** [Tencent/tdesign-mobile-vue#937]
### tdesign-mobile-vue 版本

1.0.0-rc.1

### 重现步骤

使用 WebStrom 创建新项目 -- 选择 Vite 项目 -- 使用 Vue 模板 -- 创建成功后使用`npm i tdesign-mobile-vue`安装库，并使用基础使用全量注册所有组件后，在项目中的`.vue`文件中使用 TDesign 组件

### 期望结果

在项目中`.vue`文件中输入`<t-`时出现智能补全提示，对于所有 TDesign 的组件均没有`未知 HTML 标记 t-button`的 IDE 警告

### 实际结果

输入`<t-`时没有智能提示，手动输入`<t-button size="large" theme="primary" variant="outline">描边按钮</t-button>`后 IDE 出现 1 个警告`未知 HTML 标记 t-button`

### 框架版本

3.3.4

### 浏览器版本

114.0.5735.198

### 系统版本

13.3.1

### Node版本

20.3.0

**Comment by LeeJim** [comment]
这个是你 ide 配置的问题吧

**Comment by TodayNow** [comment]
> 这个是你 ide 配置的问题吧

用别的组件库没有这个问题啊，Element Plus 和 Vant 都是正常的

**Comment by Oniokey** [comment]
通过对于 `tdesign-vue-next` 和 `tdesign-mobile-vue` 两个库，发现后者没有 `web-types.json` 且在库的 `package.json` 中也没有 `web-types` 的相关配置而前者有，是否是此原因导致 JetBrains 系列 IDE 没有智能提示以及报错`未知的 HTML 标记`呢
