### ISSUE TITLE
[Popup] 弹出层无法操作

### ISSUE THREAD

**Issue by qianxuu** [Tencent/tdesign-mobile-vue#951]
### tdesign-mobile-vue 版本

1.0.0-rc.2

### 重现链接

https://tdesign.tencent.com/mobile-vue/components/popup

### 重现步骤

官网右侧的预览也无法操作

**Comment by anlyyao** [comment]
@qianxuu 这个问题我们昨天意识到了，已修正。 你这边着急使用吗？

**Comment by qianxuu** [comment]
> @qianxuu 这个问题我们昨天意识到了，已修正。 你这边着急使用吗？

不着急，那我就先关了
