### ISSUE TITLE
[ImageViewer] 图片放大后，展示异常

### ISSUE THREAD

**Issue by huangpiqiao** [Tencent/tdesign-mobile-vue#959]
### tdesign-mobile-vue 版本

1.0.0-rc.3

### 重现链接

https://tdesign.tencent.com/mobile-vue/components/image-viewer

### 重现步骤

1.用手机扫官网上ImageViewer组件的二维码
2.点击“带操作图片预览”
3. 放大图片

### 期望结果

图片展示完整且背景没有空白

### 实际结果

图片没有展示完全，背景有空白或者图片重叠

## IssueShoot
- 预估时长: 5
- 期望完成时间: 2023-07-28 00:00:00 +0000 UTC
- 开发难度: 高
- 参与人数: 1
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by lisiqil** [comment]
认领任务

**Comment by anlyyao** [comment]
@lisiqil hello，该issue处理进度如何～
