### ISSUE TITLE
[List] 当上级节点设置了overflow-x: hidden时， list组件的scroll方法无法触发

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-mobile-vue#964]
### tdesign-mobile-vue 版本

1.0.0-rc.3

### 重现链接

https://stackblitz.com/edit/wujtgd?file=src%2Fdemo.vue

### 重现步骤

如示例，在test-dom或者 test-dom2设置了overflow-x 样式后， list组件的scroll方法无法触发

### 期望结果

overflow-x不影响list的scroll方法

### 实际结果

设置了overflow-x会影响list的scroll方法执行

### 框架版本

Vue(3.2.0)

### 浏览器版本

Chrome(99.0.4844.51)

**Comment by yaogengzhu** [comment]
import '../../_common/style/mobile/components/list/_index.less';

这个重构漏了样式改造吗？

**Comment by anlyyao** [comment]
> import '../../_common/style/mobile/components/list/_index.less';
> 
> 这个重构漏了样式改造吗？

list 组件没有新视觉～～囧

**Comment by anlyyao** [comment]
@LoopZhou 当元素指定 overflow-x: hidden 样式时，此时该元素的 overflow-y 不在是默认值 visible，而是被浏览器设置为 auto，所以会导致 List 组件无法判断正确的滚动容器。有一个解决方案是给当前元素添加 height: 100% 样式。 【欢迎一起讨论】

**Comment by ccccpj** [comment]
> @LoopZhou 当元素指定 overflow-x: hidden 样式时，此时该元素的 overflow-y 不在是默认值 visible，而是被浏览器设置为 auto，所以会导致 List 组件无法判断正确的滚动容器。有一个解决方案是给当前元素添加 height: 100% 样式。 【欢迎一起讨论】

在 父级样式添加 overscroll-behavior: contain; 可以解决这个问题

**Comment by LoopZhou** [comment]
尝试通过配置height值可解决，感谢
