### ISSUE TITLE
[upload] props的onPreview, onSuccess, onRemove, onSelectChange未触发，图片预览报错

### ISSUE THREAD

**Issue by LoopZhou** [Tencent/tdesign-mobile-vue#966]
### tdesign-mobile-vue 版本

1.0.0-rc.3

### 重现步骤

官网示例， 多选上传图片示例。
1. props配置onPreview, onSuccess, onRemove, onSelectChange未触发， event方法正常。
2. 图片预览时，图片不能显示。
<img width="829" alt="image" src="https://github.com/Tencent/tdesign-mobile-vue/assets/13745660/6aeb3e5b-ef97-40b1-ab4e-49e5494b4d27">

### 期望结果

1. props方法配置可以触发
2. 图片可以正常预览

## IssueShoot
- 预估时长: 5
- 期望完成时间: 2023-07-28 00:00:00 +0000 UTC
- 开发难度: 高
- 参与人数: 1
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by yaogengzhu** [comment]
关于 `onxxx` 方法不能触发的问题，需要你提供一个demo看看了 https://stackblitz.com/edit/fkgyfp?file=src%2Fdemo.vue

**Comment by LoopZhou** [comment]
官网示例， 多选上传图片示例： https://stackblitz.com/edit/cdm5rv?file=src%2Fdemo.vue

**Comment by yaogengzhu** [comment]
<img width="1068" alt="image" src="https://github.com/Tencent/tdesign-mobile-vue/assets/42566669/0b61c5f7-ff80-4034-83de-c57472c5530d">

似乎没问题啊

**Comment by LoopZhou** [comment]
<img width="379" alt="image" src="https://github.com/Tencent/tdesign-mobile-vue/assets/13745660/172b3648-b9c1-42a9-9f4d-52946d88474b">
<img width="603" alt="image" src="https://github.com/Tencent/tdesign-mobile-vue/assets/13745660/a8097ed5-decc-40c8-a6a1-690e5d12616e">
<img width="400" alt="image" src="https://github.com/Tencent/tdesign-mobile-vue/assets/13745660/e2a7d45d-dd7b-4526-b33c-331d28c24cf5">

onSuccess没有触发， 只有successEvent触发，其他同理。 比如移除时，onRemove就没有打印

**Comment by yaogengzhu** [comment]
看起来应该存在这个问题，项目没有对这个处理
