### ISSUE TITLE
[Popup] 多Popup下preventScrollThrough失效

### ISSUE THREAD

**Issue by TryBin03** [Tencent/tdesign-mobile-vue#969]
### tdesign-mobile-vue 版本

1.0.0-rc.3

### 重现链接

https://github.com/TryBin03/tdesignMobileVuePopupDemo

### 重现步骤

这个问题是在一个出现滚动条的页面出现A，B 两个Popup
A展示，再在A中触发事件展示B
关闭B，此时滚动页面出现滚动条（preventScrollThrough失效）

### 期望结果

滚动页面不会出现滚动条

### 实际结果

滚动页面出现滚动条

**Comment by anlyyao** [comment]
我来跟进～
