### ISSUE TITLE
[GridItem] 修改image中内容失效

### ISSUE THREAD

**Issue by TryBin03** [Tencent/tdesign-mobile-vue#974]
### tdesign-mobile-vue 版本

1.0.0-rc.4

### 重现链接

https://github.com/TryBin03/tdesignMobileVuePopupDemo

### 重现步骤

进入grid-item问题页面，点击切换按钮

### 期望结果

渲染1，2，3    上方的icon显示为 🔢，🔢🔢，🔢🔢🔢

### 实际结果

显示1，2，3   上方icon显示为 👍，🪙，⭐

**Comment by anlyyao** [comment]
@TryBin03 看着像是没有检测数组变化导致 v-for 的组件内容不更新。你可以在v-for时，加个 key属性，key表示的属性变化时，会强制更新组件～

**Comment by TryBin03** [comment]
问题解决了确实是这个问题
