### ISSUE TITLE
[Textarea] maxlength无效

### ISSUE THREAD

**Issue by huangpiqiao** [Tencent/tdesign-mobile-vue#978]
### tdesign-mobile-vue 版本

1.0.0-rc.4

### 重现链接

https://stackblitz.com/edit/3tnhcg?file=src%2Fdemo.vue

### 重现步骤

输入超过4个字符

### 期望结果

只能输入3个字母

### 实际结果

可是输入任何数量的字符

**Comment by LeeJim** [comment]
duplicated with #975
