### ISSUE TITLE
[cascader] 选择未勾选

### ISSUE THREAD

**Issue by LikeDege** [Tencent/tdesign-mobile-vue#982]
### tdesign-mobile-vue 版本

1.0.0-rc.4

### 重现步骤

使用以下的方式，选择韶关市时，仍勾选深圳市
<t-cascader
    v-model:visible="show"
    v-model:value="cascaderValue"
    title="请选择所在城市"
    :options="Cities"
    @change="onFinish"
  />
<img width="383" alt="企业微信截图_848d30e8-2fed-41eb-86a6-dec4073dccb0" src="https://github.com/Tencent/tdesign-mobile-vue/assets/12826345/215f7f07-db96-4a24-99ce-e9f1388294b3">

**Comment by anlyyao** [comment]
@LikeDege  辛苦提供完整的可复现代码，包括数据
