### ISSUE TITLE
[message] 编辑器提示类型问题

### ISSUE THREAD

**Issue by ry0513** [Tencent/tdesign-mobile-vue#984]
### tdesign-mobile-vue 版本

1.0.0-rc.4

### 重现步骤

![image](https://github.com/Tencent/tdesign-mobile-vue/assets/44745967/dced8f50-851d-42f2-9e51-14e4686a133a)
![image](https://github.com/Tencent/tdesign-mobile-vue/assets/44745967/f783f938-84ef-4303-bab7-677d7a4330fe)
TdMessageProps 类型如下：
```js
// 并没有定义 context 类型
export interface TdMessageProps {
    align?: MessageAlignType;
    closeBtn?: string | boolean | TNode;
    content?: string | TNode;
    duration?: number;
    icon?: boolean | TNode;
    link?: string | object | TNode;
    marquee?: boolean | DrawMarquee;
    offset?: Array<string | number>;
    theme?: MessageThemeList;
    visible?: boolean;
    defaultVisible?: boolean;
    modelValue?: boolean;
    zIndex?: number;
    onCloseBtnClick?: (context: {
        e: MouseEvent;
    }) => void;
    onDurationEnd?: () => void;
    onLinkClick?: (context: {
        e: MouseEvent;
    }) => void;
}
```

**Comment by ry0513** [comment]
![image](https://github.com/Tencent/tdesign-mobile-vue/assets/44745967/9a1766ca-cd91-46ba-b58a-d1162287505a)
js 调用时在自动关闭侯会报错，官网复现 [https://tdesign.tencent.com/mobile-vue/components/message](https://tdesign.tencent.com/mobile-vue/components/message)

**Comment by anlyyao** [comment]
收到反馈，我来看看～
